apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-db
  labels:
    app: recipes
spec:
  selector:
    matchLabels:
      tier: db
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-media
  labels:
    app: recipes
spec:
  selector:
    matchLabels:
      tier: media
      app: recipes
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes-static
  labels:
    app: recipes
spec:
  selector:
    matchLabels:
      tier: static
      app: recipes
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
