apiVersion: v1
kind: Service
metadata:
  name: recipes
  labels:
    app: recipes
spec:
  selector:
    app: recipes
    environment: production
  ports:
  - port: 80
    targetPort: http
    name: http
    protocol: TCP
