# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "pip"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    cooldown:
      semver-major-days: 30
      semver-minor-days: 3
      semver-patch-days: 3
    directory: "/"
    groups:
      pip-patches:
        patterns: ["*"]
        update-types: ["patch"]
      pip-minors:
        patterns: ["*"]
        update-types: ["minor"]
    
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "python"
      - "dependencies"
      - "automerge"

  - package-ecosystem: "npm"
    open-pull-requests-limit: 20
    schedule:
      interval: "monthly"
    cooldown:
      semver-major-days: 30
      semver-minor-days: 3
      semver-patch-days: 3
    directory: "/vue/"
    ignore:
      - dependency-name: "*vue*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pinia*"
        update-types: ["version-update:semver-major"]
    groups:
      npm-patches:
        patterns: ["*"]
        update-types: ["patch"]
      npm-minors:
        patterns: ["*"]
        update-types: ["minor"]
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "javascript"
      - "dependencies"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    directory: "/"
    groups:
      actions-updates:
          patterns: ["*"]
          update-types: ["patch", "minor"]
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "github-actions"
      - "automerge"

  - package-ecosystem: "docker"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    directory: "/"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "docker"
      - "dependencies"
      - "automerge"

  - package-ecosystem: "devcontainers"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    directory: "/"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "devcontainer"
      - "dependencies"
      - "automerge"
