# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "devcontainer"
      - "dependencies"
      - "automerge"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      semver-major-days: 30
      semver-minor-days: 3  
      semver-patch-days: 3
    groups:
      pip-patches:
        patterns: ["*"]
        update-types: ["patch"]
      pip-minors:
        patterns: ["*"]
        update-types: ["minor"]
    open-pull-requests-limit: 10
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "python"
      - "dependencies"
      - "automerge"

  - package-ecosystem: "npm"
    directory: "/vue/"
    groups:
      npm-patches:
        patterns: ["*"]
        update-types: ["patch"]
      npm-minors:
        patterns: ["*"]
        update-types: ["minor"]
    schedule:
      interval: "monthly"
    cooldown:
      semver-major-days: 30
      semver-minor-days: 3  
      semver-patch-days: 3
    open-pull-requests-limit: 5
    versioning-strategy: "increase-if-necessary"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    allow:
      - dependency-type: "direct"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
      - dependency-type: "indirect"
        update-types: ["version-update:semver-patch", "version-update:semver-minor"]
    labels:
      - "javascript"
      - "vue"
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      actions-updates:
          patterns: ["*"]
          update-types: ["patch", "minor"]
    schedule:
      interval: "weekly"
    cooldown:
      semver-major-days: 30
      semver-minor-days: 3  
      semver-patch-days: 3
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "github-actions"
      - "automerge"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      semver-major-days: 30
      semver-minor-days: 3  
      semver-patch-days: 3
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    labels:
      - "docker"
      - "dependencies"
      - "automerge"
