
version: 2
updates:
  - package-ecosystem: "pip"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    cooldown:
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 3
      exclude:
        - "recipe-scrapers"
    directory: "/"
    groups:
      pip-patches:
        exclude-patterns: ["pytest*"]
        update-types: ["patch"]
      pip-minors:
        exclude-patterns: ["pytest*"]
        update-types: ["minor"]
      pip-pytest:
        patterns: ["pytest*"]
        update-types: ["minor", "patch"]

    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "python"
      - "dependencies"
      - "automerge"

  - package-ecosystem: "npm"
    open-pull-requests-limit: 20
    schedule:
      interval: "monthly"
    cooldown:
      semver-major-days: 30
      semver-minor-days: 3
      semver-patch-days: 3
    directory: "vue"
    ignore:
      - dependency-name: "*vue"
        update-types: ["version-update:semver-major"]
      - dependency-name: "*vue*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "pinia*"
        update-types: ["version-update:semver-major"]
    groups:
      npm-patches:
        patterns: ["*"]
        update-types: ["patch"]
      npm-minors:
        patterns: ["*"]
        update-types: ["minor"]
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "javascript"
      - "dependencies"

  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 20
    schedule:
      interval: "weekly"
    directory: "/.github/"
    groups:
      actions-updates:
          patterns: ["*"]
          update-types: ["patch", "minor"]
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "github_actions"
      - "dependencies"
      - "automerge"

  - package-ecosystem: "docker"
    open-pull-requests-limit: 5
    schedule:
      interval: "weekly"
    directory: "/"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "docker"
      - "dependencies"

