/* tslint:disable */
/* eslint-disable */
/**
 * Django Recipes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InviteLinkGroup
 */
export interface InviteLinkGroup {
    /**
     * 
     * @type {number}
     * @memberof InviteLinkGroup
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof InviteLinkGroup
     */
    name: string;
}

/**
 * Check if a given object implements the InviteLinkGroup interface.
 */
export function instanceOfInviteLinkGroup(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function InviteLinkGroupFromJSON(json: any): InviteLinkGroup {
    return InviteLinkGroupFromJSONTyped(json, false);
}

export function InviteLinkGroupFromJSONTyped(json: any, ignoreDiscriminator: boolean): InviteLinkGroup {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
    };
}

export function InviteLinkGroupToJSON(value?: InviteLinkGroup | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

