# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: pre-commit-yarn-build
        name: Build javascript files
        entry: yarn --cwd ./vue build
        always_run: true
        language: system
        types: [ python ]
        pass_filenames: false

#- id: pre-commit-django-migrations
#        name: Check django migrations
#        entry: bash -c './venv/bin/activate && ./manage.py makemigrations --check'
#        language: system
#        types: [ python ]
#        pass_filenames: false
#      - id: pre-commit-django-make-messages
#        name: Make messages if necessary
#        entry: ./manage.py makemessages -i venv -a
#        language: system
#        types: [ python ]
#        pass_filenames: false
#      - id: pre-commit-django-compile-messages
#        name: Compile messages if necessary
#        entry: ./manage.py compilemessages -i venv
#        language: system
#        types: [ python ]
#        pass_filenames: false