site_name: Tandoor Recipes
site_description: Tandoor Recipe Documentation
site_author: vabene1111
repo_url: https://github.com/vabene1111/recipes
edit_uri: https://github.com/vabene1111/recipes/tree/develop/docs
extra_css:
  - stylesheets/extra.css

theme:
  name: material
  repo: fontawesome/brands/github
  logo: logo_color.svg
  favicon: logo_color.svg
  palette:
    scheme: slate



markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - include-markdown
  - search

nav:
  - Home: 'index.md'
  - Installation:
      - Docker: install/docker.md
      - Unraid: install/unraid.md
      - Synology: install/synology.md
      - Kubernetes: install/kubernetes.md
      - KubeSail or PiBox: install/kubesail.md
      - TrueNAS Portainer: install/truenas_portainer.md
      - WSL: install/wsl.md
      - ArchLinux: install/archlinux.md
      - HomeAssistant: install/homeassistant.md
      - Manual: install/manual.md
      - Other setups: install/other.md
  - Features:
      - Templating: features/templating.md
      - Shopping: features/shopping.md
      - Authentication: features/authentication.md
      - Automation: features/automation.md
      - Connectors: features/connectors.md
      - Storages and Sync: features/external_recipes.md
      - Import/Export: features/import_export.md
      - Telegram bot: features/telegram_bot.md
  - System:
      - Configuration: system/configuration.md
      - Updating: system/updating.md
      - Migrate sqlite to postgres: system/migration_sqlite-postgres.md
      - Permission System: system/permissions.md
      - Backup: system/backup.md
  - Contributing:
      - Overview: contribute/contribute.md
      - Translations: contribute/translations.md
      - Documentation: contribute/documentation.md
      - Code: contribute/guidelines.md
      - Installation: contribute/installation.md
      - IDE Setup:
          - VSCode: contribute/vscode.md
          - PyCharm: contribute/pycharm.md
      - Related Projects: contribute/related.md
  - FAQ: faq.md
