name: Documentation Issue
description: "Create a report to help us improve"
#title: ""
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation issue report!
  - type: input
    id: docs-link
    attributes:
      label: Documentation link
      description: "Please provide a link to the corresponding documentation site on docs.tandoor.dev"
  - type: dropdown
    id: section
    attributes:
      label: Affected section
      description: "What part of the documentation is the issue about?"
      options:
        - Installation
        - Features
        - System
        - FAQ
        - Does not exist yet
        - Other (please state below)
    validations:
      required: true
  - type: input
    id: other
    attributes:
      label: Other
      description: "In case you chose 'Other' above, please provide more info here."
  - type: textarea
    id: descr
    attributes:
      label: Issue description
      description: "Please accurately describe the documentation issue you are seeing."
    validations:
      required: true
