name: Website Import
description: "Anything related to website imports"
#title: ""
#labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this website import form!
  - type: input
    id: version
    attributes:
      label: Tandoor Version
      description: "What version of Tandoor are you using? (can be found on the system page since v0.8.4)"
    validations:
      required: true
  - type: input
    id: url
    attributes:
      label: Import URL
      description: "Exact URL you are trying to import from."
    validations:
      required: true
  - type: textarea
    id: bug-descr
    attributes:
      label: "When did the issue happen?"
      description: "When pressing the search button with the url / when importing after the page has loaded / ..."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Response / message shown
      description: Please copy and paste any relevant logs or responses / messages which are shown in Tandoor. This will be automatically formatted into code, so no need for backticks.
      render: shell
