version: "3"
services:
  db_recipes:
    restart: always
    image: postgres:11-alpine
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - ./.env
    networks:
      - default

  web_recipes:
    image: vabene1111/recipes
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./staticfiles:/opt/recipes/staticfiles
      - ./mediafiles:/opt/recipes/mediafiles
    depends_on:
      - db_recipes
    networks:
      - default

    nginx_recipes:
      image: nginx:mainline-alpine
      restart: always
      env_file:
        - ./.env
      volumes:
        - ./nginx/conf.d:/etc/nginx/conf.d
        - ./staticfiles:/static
        - ./mediafiles:/media
      networks:
        - default
        - nginx-proxy

networks:
  default:
  nginx-proxy:
    external:
      name: nginx-proxy