# Generated by Django 2.0.5 on 2018-05-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='synclog',
            old_name='monitor',
            new_name='sync',
        ),
    ]
