# Generated by Django 2.0.5 on 2018-06-06 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='storage_uid',
            new_name='file_uid',
        ),
        migrations.RenameField(
            model_name='recipeimport',
            old_name='storage_uid',
            new_name='file_uid',
        ),
    ]
