# Generated by Django 2.0.2 on 2018-02-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20180201_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='path',
            field=models.CharField(default='', max_length=512),
            preserve_default=False,
        ),
    ]
