# Generated by Django 2.2.7 on 2019-11-13 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20191113_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='storage',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='cookbook.Storage'),
        ),
    ]
