# Generated by Django 2.0.5 on 2018-05-25 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20180525_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeimport',
            name='storage',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='cookbook.Storage'),
            preserve_default=False,
        ),
    ]
