# Generated by Django 2.2.7 on 2019-11-13 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0003_auto_20191113_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='storage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cookbook.Storage'),
        ),
    ]
