# Generated by Django 2.2.7 on 2019-11-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0004_auto_20191113_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredients',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
