# Generated by Django 2.2.7 on 2019-11-15 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0009_auto_20191114_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='internal',
            field=models.BooleanField(default=False),
        ),
    ]
