# Generated by Django 3.0.2 on 2020-01-30 09:59

from django.db import migrations


def migrate_ingredient_units(apps, schema_editor):
    Unit = apps.get_model('cookbook', 'Unit')
    RecipeIngredient = apps.get_model('cookbook', 'RecipeIngredient')

    for u in RecipeIngredient.objects.values('unit').distinct():
        unit = Unit()
        unit.name = u['unit']
        unit.save()

    for i in RecipeIngredient.objects.all():
        i.unit_key = Unit.objects.get(name=i.unit)
        i.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0009_auto_20200130_1056'),
    ]

    operations = [
        migrations.RunPython(migrate_ingredient_units),
    ]
