# Generated by Django 2.2.7 on 2019-11-15 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0010_recipe_internal'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='time',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
