# Generated by Django 3.0.2 on 2020-01-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0011_remove_recipeingredients_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredients',
            old_name='unit_key',
            new_name='unit',
        ),
    ]
