# Generated by Django 3.0.2 on 2020-02-16 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0022_remove_recipeingredient_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='ingredient',
            new_name='name',
        ),
    ]
