# Generated by Django 3.0.2 on 2020-02-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0024_auto_20200216_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='nav_color',
            field=models.CharField(choices=[('PRIMARY', 'Primary'), ('SECONDARY', 'Secondary'), ('SUCCESS', 'Success'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('DANGER', 'Danger'), ('LIGHT', 'Light'), ('DARK', 'Dark')], default='PRIMARY', max_length=128),
        ),
    ]
