# Generated by Django 3.0.4 on 2020-04-07 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0030_recipeingredient_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='icon',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
