# Generated by Django 3.0.4 on 2020-04-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0031_auto_20200407_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='default_unit',
            field=models.CharField(default='g', max_length=32),
        ),
    ]
