# Generated by Django 3.0.4 on 2020-04-13 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0032_userpreference_default_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='default_page',
            field=models.CharField(choices=[('SEARCH', 'Search'), ('PLAN', 'Meal-Plan')], default='SEARCH', max_length=64),
        ),
    ]
