# Generated by Django 3.0.5 on 2020-04-27 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0034_auto_20200426_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mealplan',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RenameField(
            model_name='recipebook',
            old_name='user',
            new_name='created_by',
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='default_page',
            field=models.CharField(choices=[('SEARCH', 'Search'), ('PLAN', 'Meal-Plan'), ('BOOKS', 'Books')], default='SEARCH', max_length=64),
        ),
    ]
