# Generated by Django 3.0.5 on 2020-05-02 12:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbook', '0038_auto_20200502_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebook',
            name='shared',
            field=models.ManyToManyField(blank=True, related_name='shared_with', to=settings.AUTH_USER_MODEL),
        ),
    ]
