# Generated by Django 3.0.5 on 2020-05-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0040_auto_20200502_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='title',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cookbook.Recipe'),
        ),
    ]
