# Generated by Django 3.0.5 on 2020-06-02 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0044_viewlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='show_recent',
            field=models.BooleanField(default=True),
        ),
    ]
