# Generated by Django 3.0.7 on 2020-06-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0051_auto_20200611_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='ingredient_decimals',
            field=models.IntegerField(default=2),
        ),
    ]
