# Generated by Django 3.0.7 on 2020-06-25 19:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('cookbook', '0057_auto_20200625_2127'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredient',
            new_name='Ingredient',
        ),
        migrations.AlterField(
            model_name='sharelink',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('27328011-54fb-46fa-8846-424d5828d858')),
        ),
    ]
