# Generated by Django 3.0.7 on 2020-06-25 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0062_auto_20200625_2219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='instructions',
        ),
    ]
