# Generated by Django 3.0.7 on 2020-06-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0066_auto_20200626_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='note',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
