# Generated by Django 3.0.7 on 2020-07-01 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0069_auto_20200629_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='time',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='step',
            name='kind',
            field=models.CharField(choices=[('TEXT', 'Text'), ('TIME', 'Time')], default='TEXT', max_length=16),
        ),
    ]
