# Generated by Django 3.0.7 on 2020-07-01 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0070_auto_20200701_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='step',
            old_name='kind',
            new_name='type',
        ),
    ]
