# Generated by Django 3.0.7 on 2020-09-22 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0081_auto_20200921_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='valid_until',
            field=models.DateField(default=datetime.date(2020, 10, 6)),
        ),
        migrations.AlterField(
            model_name='shoppinglistentry',
            name='amount',
            field=models.DecimalField(decimal_places=16, default=0, max_digits=32),
        ),
    ]
