# Generated by Django 3.0.7 on 2020-09-29 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0085_auto_20200922_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='recipe_multiplier',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='valid_until',
            field=models.DateField(default=datetime.date(2020, 10, 13)),
        ),
    ]
