# Generated by Django 3.0.7 on 2020-09-29 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0086_auto_20200929_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='recipe_multiplier',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=8),
        ),
        migrations.AlterField(
            model_name='shoppinglistrecipe',
            name='multiplier',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=8),
        ),
    ]
