# Generated by Django 3.1.1 on 2020-09-29 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0087_auto_20200929_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
