# Generated by Django 3.1.1 on 2020-11-17 21:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0088_shoppinglist_finished'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fats', models.DecimalField(decimal_places=16, default=0, max_digits=32)),
                ('carbohydrates', models.DecimalField(decimal_places=16, default=0, max_digits=32)),
                ('proteins', models.DecimalField(decimal_places=16, default=0, max_digits=32)),
                ('calories', models.DecimalField(decimal_places=16, default=0, max_digits=32)),
                ('source', models.CharField(blank=True, default='', max_length=512, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='invitelink',
            name='valid_until',
            field=models.DateField(default=datetime.date(2020, 12, 1)),
        ),
        migrations.AddField(
            model_name='recipe',
            name='nutrition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cookbook.nutritioninformation'),
        ),
    ]
