# Generated by Django 3.1.5 on 2021-01-13 12:15

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0096_auto_20210109_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=128, unique=True, validators=[django.core.validators.MinLengthValidator(1)]),
        ),
    ]
