# Generated by Django 3.1.5 on 2021-01-13 12:20

import cookbook.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0097_auto_20210113_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitelink',
            name='valid_until',
            field=models.DateField(default=cookbook.models.default_valid_until),
        ),
    ]
