# Generated by Django 3.1.5 on 2021-01-26 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0104_auto_20210125_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermarketcategoryrelation',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_to_supermarket', to='cookbook.supermarketcategory'),
        ),
        migrations.AlterField(
            model_name='supermarketcategoryrelation',
            name='supermarket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_to_supermarket', to='cookbook.supermarket'),
        ),
    ]
