# Generated by Django 3.1.5 on 2021-01-26 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0105_auto_20210126_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='supermarket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cookbook.supermarket'),
        ),
    ]
