# Generated by Django 3.1.6 on 2021-02-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0107_auto_20210128_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='cooklog',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='invitelink',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='keyword',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealplan',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mealtype',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipebook',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipebookentry',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipeimport',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sharelink',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglistentry',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglistrecipe',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storage',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supermarket',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supermarketcategory',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sync',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='synclog',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpreference',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='viewlog',
            name='space',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
            preserve_default=False,
        ),
    ]
