# Generated by Django 3.1.6 on 2021-02-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0109_auto_20210221_1204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='space',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
        ),
    ]
