# Generated by Django 3.1.7 on 2021-03-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0111_space_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='synclog',
            name='space',
        ),
    ]
