# Generated by Django 3.1.7 on 2021-03-17 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0112_remove_synclog_space'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppinglistentry',
            name='space',
        ),
        migrations.RemoveField(
            model_name='shoppinglistrecipe',
            name='space',
        ),
    ]
