# Generated by Django 3.2 on 2021-04-11 19:01
from django.contrib.postgres.operations import UnaccentExtension, TrigramExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0118_auto_20210406_1805'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
    ]
