# Generated by Django 3.2.3 on 2021-05-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0120_bookmarklet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='search_style',
            field=models.CharField(choices=[('SMALL', 'Small'), ('LARGE', 'Large'), ('NEW', 'New')], default='LARGE', max_length=64),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='use_fractions',
            field=models.BooleanField(default=True),
        ),
    ]
