# Generated by Django 3.2.3 on 2021-05-27 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0121_auto_20210518_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='allow_files',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='space',
            name='max_users',
            field=models.IntegerField(default=0),
        ),
    ]
