# Generated by Django 3.2.3 on 2021-05-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0122_auto_20210527_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelink',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
