# Generated by Django 3.2.3 on 2021-06-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0124_alter_userpreference_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='demo',
            field=models.BooleanField(default=False),
        ),
    ]
