# Generated by Django 3.2.3 on 2021-06-07 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0126_alter_userpreference_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitelink',
            name='username',
        ),
    ]
