# Generated by Django 3.2.3 on 2021-06-08 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0128_userfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='allow_files',
        ),
        migrations.AddField(
            model_name='space',
            name='max_file_storage_mb',
            field=models.IntegerField(default=0, help_text='Maximum file storage for space in MB. 0 for unlimited, -1 to disable file upload.'),
        ),
    ]
