# Generated by Django 3.2.4 on 2021-06-08 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0130_alter_userfile_file_size_kb'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cookbook.userfile'),
        ),
        migrations.AlterField(
            model_name='step',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('TIME', 'Time'), ('FILE', 'File')], default='TEXT', max_length=16),
        ),
    ]
