# Generated by Django 3.2.4 on 2021-06-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0131_auto_20210608_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='request_count',
            field=models.IntegerField(default=0),
        ),
    ]
