# Generated by Django 3.2.4 on 2021-06-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0133_sharelink_abuse_blocked'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='allow_sharing',
            field=models.BooleanField(default=True),
        ),
    ]
