# Generated by Django 3.2.4 on 2021-06-17 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0135_auto_20210615_2210'),
    ]

    operations = [
        migrations.AddField(
            model_name='importlog',
            name='imported_recipes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='importlog',
            name='total_recipes',
            field=models.IntegerField(default=0),
        ),
    ]
