# Generated by Django 3.2.4 on 2021-06-17 14:02

from django.db import migrations
from django.db.models import Subquery, OuterRef
from django_scopes import scopes_disabled
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('cookbook', '0137_auto_20210617_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
        ),
        migrations.AlterField(
            model_name='nutritioninformation',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
        ),
        migrations.AlterField(
            model_name='step',
            name='space',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.space'),
        ),
    ]
