# Generated by Django 3.2.4 on 2021-06-22 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0139_space_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
