# Generated by Django 3.2.5 on 2021-07-13 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0140_userpreference_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='step',
            name='step_recipe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='cookbook.recipe'),
        ),
        migrations.AlterField(
            model_name='step',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('TIME', 'Time'), ('FILE', 'File'), ('RECIPE', 'Recipe')], default='TEXT', max_length=16),
        ),
    ]
