# Generated by Django 3.2.5 on 2021-07-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0141_auto_20210713_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='search_style',
            field=models.CharField(choices=[('SMALL', 'Small'), ('LARGE', 'Large'), ('NEW', 'New')], default='NEW', max_length=64),
        ),
    ]
