# Generated by Django 3.2.5 on 2021-08-13 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0147_keyword_to_tree'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='keyword',
            name='unique_name_per_space',
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='use_fractions',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='food',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='recipebookentry',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supermarket',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='supermarketcategory',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='food',
            constraint=models.UniqueConstraint(fields=('space', 'name'), name='f_unique_name_per_space'),
        ),
        migrations.AddConstraint(
            model_name='keyword',
            constraint=models.UniqueConstraint(fields=('space', 'name'), name='kw_unique_name_per_space'),
        ),
        migrations.AddConstraint(
            model_name='recipebookentry',
            constraint=models.UniqueConstraint(fields=('recipe', 'book'), name='rbe_unique_name_per_space'),
        ),
        migrations.AddConstraint(
            model_name='supermarket',
            constraint=models.UniqueConstraint(fields=('space', 'name'), name='sm_unique_name_per_space'),
        ),
        migrations.AddConstraint(
            model_name='supermarketcategory',
            constraint=models.UniqueConstraint(fields=('space', 'name'), name='smc_unique_name_per_space'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('space', 'name'), name='u_unique_name_per_space'),
        ),
    ]
