# Generated by Django 3.2.7 on 2021-09-15 21:27

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0152_automation'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='cooklog',
            name='cookbook_co_id_93d841_idx',
        ),
        migrations.RemoveIndex(
            model_name='food',
            name='cookbook_fo_id_22b733_idx',
        ),
        migrations.RemoveIndex(
            model_name='ingredient',
            name='cookbook_in_id_3368be_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='cookbook_re_name_se_bdf3ca_gin',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='cookbook_re_id_e4c2d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipebook',
            name='cookbook_re_name_bbe446_idx',
        ),
        migrations.AddIndex(
            model_name='cooklog',
            index=models.Index(fields=['id'], name='cookbook_co_id_553a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='cooklog',
            index=models.Index(fields=['recipe'], name='cookbook_co_recipe__8ec719_idx'),
        ),
        migrations.AddIndex(
            model_name='cooklog',
            index=models.Index(fields=['-created_at'], name='cookbook_co_created_f6e244_idx'),
        ),
        migrations.AddIndex(
            model_name='cooklog',
            index=models.Index(fields=['rating'], name='cookbook_co_rating_aa7662_idx'),
        ),
        migrations.AddIndex(
            model_name='cooklog',
            index=models.Index(fields=['created_by'], name='cookbook_co_created_7ea086_idx'),
        ),
        migrations.AddIndex(
            model_name='cooklog',
            index=models.Index(fields=['created_by', 'rating'], name='cookbook_co_created_f5ccd7_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['id'], name='cookbook_fo_id_3c379b_idx'),
        ),
        migrations.AddIndex(
            model_name='food',
            index=models.Index(fields=['name'], name='cookbook_fo_name_c848b6_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredient',
            index=models.Index(fields=['id'], name='cookbook_in_id_2c1f57_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name_search_vector'], name='cookbook_re_name_se_5dbbd5_gin'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=django.contrib.postgres.indexes.GinIndex(fields=['desc_search_vector'], name='cookbook_re_desc_se_fdee30_gin'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['id'], name='cookbook_re_id_b2bdcf_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['name'], name='cookbook_re_name_b8a027_idx'),
        ),
        migrations.AddIndex(
            model_name='recipebook',
            index=models.Index(fields=['name'], name='cookbook_re_name_94cc63_idx'),
        ),
        migrations.AddIndex(
            model_name='viewlog',
            index=models.Index(fields=['recipe'], name='cookbook_vi_recipe__ce995d_idx'),
        ),
        migrations.AddIndex(
            model_name='viewlog',
            index=models.Index(fields=['-created_at'], name='cookbook_vi_created_bd2b5f_idx'),
        ),
        migrations.AddIndex(
            model_name='viewlog',
            index=models.Index(fields=['created_by'], name='cookbook_vi_created_f9385c_idx'),
        ),
    ]
