# Generated by Django 3.2.7 on 2021-09-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0153_auto_20210915_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtype',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='mealtype',
            name='icon',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
