# Generated by Django 3.2.7 on 2021-09-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0154_auto_20210922_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealtype',
            name='default',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
