# Generated by Django 3.2.7 on 2021-09-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0155_mealtype_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchpreference',
            name='trigram_threshold',
            field=models.DecimalField(decimal_places=2, default=0.1, max_digits=3),
        ),
    ]
