# Generated by Django 3.2.7 on 2021-10-01 20:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


def copy_values_to_sle(apps, schema_editor):
    ShoppingListEntry = apps.get_model('app', 'ShoppingListEntry')
    db_alias = schema_editor.connection.alias
    from django.db.models import F
    MetaDataValue.objects.using(db_alias).all().update(
        short_value=F('shoppinglist__created_by')
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbook', '0157_alter_searchpreference_trigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='on_hand',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppinglistentry',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglistentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglistentry',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoppinglistentry',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cookbook.recipe'),
        ),
        migrations.AddField(
            model_name='userpreference',
            name='shopping_share',
            field=models.ManyToManyField(blank=True, related_name='shopping_share', to=settings.AUTH_USER_MODEL),
        ),
    ]
