# Generated by Django 3.2.7 on 2021-10-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0157_alter_searchpreference_trigram'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='use_kj',
            field=models.BooleanField(default=False),
        ),
    ]
