# Generated by Django 3.2.7 on 2021-10-01 22:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc

from django_scopes import scopes_disabled
from cookbook.models import ShoppingListEntry


def delete_orphaned_sle(apps, schema_editor):
    with scopes_disabled():
        # shopping list entry is orphaned - delete it
        ShoppingListEntry.objects.filter(shoppinglist=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbook', '0159_add_shoppinglistentry_fields'),
    ]

    operations = [
        migrations.RunPython(delete_orphaned_sle),
    ]
