# Generated by Django 3.2.8 on 2021-11-03 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0160_delete_shoppinglist_orphans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppinglistentry',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_entries', to='cookbook.food'),
        ),
    ]
