# Generated by Django 3.2.10 on 2021-12-29 20:11

from django.db import migrations

from cookbook.models import FoodInheritField

# TODO this can be deleted
# def temp_migration(apps, schema_editor):
#     x = FoodInheritField.objects.get(name='Ignore Shopping', field='ignore_shopping')
#     x.name = 'On Hand'
#     x.field = 'food_onhand'
#     x.save


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0162_userpreference_csv_delim'),
    ]

    operations = [
        # TODO this can be deleted
        # migrations.RunPython(temp_migration),
        # TODO this stays
        migrations.RenameField(
            model_name='food',
            old_name='ignore_shopping',
            new_name='food_onhand',
        ),
        # TODO this can be deleted
        # migrations.RemoveField(
        #     model_name='food',
        #     name='on_hand',
        # ),
    ]
