# Generated by Django 3.2.11 on 2022-01-08 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0164_exportlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportlog',
            name='cache_duration',
            field=models.IntegerField(default=0),
        ),
    ]
