# Generated by Django 3.2.11 on 2022-01-08 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0165_exportlog_cache_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportlog',
            name='possibly_not_expired',
            field=models.BooleanField(default=True),
        ),
    ]
