# Generated by Django 3.2.12 on 2022-02-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0170_auto_20220207_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchpreference',
            name='trigram_threshold',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=3),
        ),
    ]
