# Generated by Django 3.2.11 on 2022-02-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0171_auto_20220202_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='child_inherit_fields',
            field=models.ManyToManyField(blank=True, related_name='child_inherit', to='cookbook.FoodInheritField'),
        ),
    ]
