# Generated by Django 3.2.12 on 2022-03-04 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0172_ingredient_original_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.CharField(blank=True, default=None, max_length=1024, null=True),
        ),
    ]
