# Generated by Django 4.0.6 on 2022-07-12 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0177_recipe_show_ingredient_overview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpreference',
            name='search_style',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='show_recent',
        ),
    ]
