# Generated by Django 4.0.6 on 2022-07-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0179_recipe_private_recipe_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelink',
            name='reusable',
            field=models.BooleanField(default=False),
        ),
    ]
