# Generated by Django 4.0.6 on 2022-07-14 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0180_invitelink_reusable'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space_image', to='cookbook.userfile'),
        ),
    ]
