# Generated by Django 4.0.6 on 2022-07-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0181_space_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_image', to='cookbook.userfile'),
        ),
    ]
