# Generated by Django 4.0.6 on 2022-08-04 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0182_userpreference_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space_image', to='cookbook.userfile'),
        ),
    ]
