# Generated by Django 4.0.7 on 2022-09-12 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0183_alter_space_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_image', to='cookbook.userfile'),
        ),
    ]
