# Generated by Django 4.1.4 on 2023-01-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0185_food_plural_name_ingredient_always_use_plural_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='order',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='automation',
            name='type',
            field=models.CharField(choices=[('FOOD_ALIAS', 'Food Alias'), ('UNIT_ALIAS', 'Unit Alias'), ('KEYWORD_ALIAS', 'Keyword Alias'), ('DESCRIPTION_REPLACE', 'Description Replace'), ('INSTRUCTION_REPLACE', 'Instruction Replace')], max_length=128),
        ),
    ]
