# Generated by Django 4.1.4 on 2023-01-20 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0186_automation_order_alter_automation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='space',
            name='use_plural',
            field=models.BooleanField(default=True),
        ),
    ]
