# Generated by Django 4.1.4 on 2023-02-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0187_alter_space_use_plural'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='no_sharing_limit',
            field=models.BooleanField(default=False),
        ),
    ]
