# Generated by Django 4.1.7 on 2023-03-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0189_unit_base_unit_unitconversion_foodpropertytype_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='foodproperty',
            name='food_nutrition_unique_per_space',
        ),
        migrations.RemoveConstraint(
            model_name='foodpropertytype',
            name='nutrition_type_unique_name_per_space',
        ),
        migrations.RenameField(
            model_name='foodproperty',
            old_name='nutrition_amount',
            new_name='property_amount',
        ),
        migrations.RenameField(
            model_name='foodproperty',
            old_name='nutrition_type',
            new_name='property_type',
        ),
        migrations.AlterField(
            model_name='foodpropertytype',
            name='category',
            field=models.CharField(blank=True, choices=[('NUTRITION', 'Nutrition'), ('ALLERGEN', 'Allergen'), ('PRICE', 'PRICE')], max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='foodproperty',
            constraint=models.UniqueConstraint(fields=('food', 'property_type', 'space'), name='food_property_unique_per_space'),
        ),
        migrations.AddConstraint(
            model_name='foodpropertytype',
            constraint=models.UniqueConstraint(fields=('space', 'name'), name='food_property_type_unique_name_per_space'),
        ),
    ]
