# Generated by Django 4.1.7 on 2023-02-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0190_nutritiontype_foodnutrition'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='foodnutrition',
            constraint=models.UniqueConstraint(fields=('food', 'nutrition_type', 'space'), name='food_nutrition_unique_per_space'),
        ),
        migrations.AddConstraint(
            model_name='nutritiontype',
            constraint=models.UniqueConstraint(fields=('space', 'name'), name='nutrition_type_unique_name_per_space'),
        ),
    ]
