# Generated by Django 4.1.7 on 2023-05-04 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0192_remove_foodpropertytype_fdc_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='unitconversion',
            constraint=models.UniqueConstraint(fields=('space', 'base_unit', 'converted_unit', 'food'), name='f_unique_conversion_per_space'),
        ),
    ]
