# Generated by Django 4.1.7 on 2023-02-26 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0192_alter_unitconversion_base_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitconversion',
            name='base_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversion_base_relation', to='cookbook.unit'),
        ),
        migrations.AlterField(
            model_name='unitconversion',
            name='converted_unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversion_converted_relation', to='cookbook.unit'),
        ),
    ]
