# Generated by Django 4.1.7 on 2023-03-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0193_alter_unitconversion_base_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='base_unit',
            field=models.TextField(blank=True, default=None, max_length=256, null=True),
        ),
    ]
