# Generated by Django 4.1.9 on 2023-06-26 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0193_space_internal_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='properties_food_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=100, max_digits=16),
        ),
    ]
