# Generated by Django 4.1.7 on 2023-05-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0193_unitconversion_f_unique_conversion_per_space'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='supermarketcategoryrelation',
            constraint=models.UniqueConstraint(fields=('supermarket', 'category'), name='unique_sm_category_relation'),
        ),
    ]
