# Generated by Django 4.1.9 on 2023-06-30 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0194_alter_food_properties_food_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelink',
            name='internal_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userspace',
            name='internal_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userspace',
            name='invite_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cookbook.invitelink'),
        ),
        migrations.AlterField(
            model_name='userpreference',
            name='theme',
            field=models.CharField(choices=[('TANDOOR', 'Tandoor'), ('BOOTSTRAP', 'Bootstrap'), ('DARKLY', 'Darkly'), ('FLATLY', 'Flatly'), ('SUPERHERO', 'Superhero'), ('TANDOOR_DARK', 'Tandoor Dark (INCOMPLETE)')], default='TANDOOR', max_length=128),
        ),
    ]
