# Generated by Django 4.1.7 on 2023-05-06 16:33

import cookbook.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0194_supermarketcategoryrelation_unique_sm_category_relation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FoodPropertyType',
            new_name='PropertyType',
        ),
        migrations.CreateModel(
            name='RecipeProperty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_amount', models.DecimalField(decimal_places=4, default=0, max_digits=32)),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cookbook.propertytype')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.space')),
            ],
            bases=(models.Model, cookbook.models.PermissionModelMixin),
        ),
        migrations.AddField(
            model_name='recipe',
            name='properties',
            field=models.ManyToManyField(blank=True, to='cookbook.recipeproperty'),
        ),
    ]
