# Generated by Django 4.1.10 on 2023-07-22 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0195_invitelink_internal_note_userspace_internal_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='url',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
