# Generated by Django 4.1.10 on 2023-08-24 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0197_step_show_ingredients_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
