# Generated by Django 4.1.10 on 2023-09-07 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0200_alter_propertytype_options_remove_keyword_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='space',
            name='show_facet_count',
        ),
    ]
