# Generated by Django 4.2.7 on 2023-11-27 21:09

from django.db import migrations, models
from django_scopes import scopes_disabled




class Migration(migrations.Migration):
    dependencies = [
        ('cookbook', '0203_alter_unique_contstraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertytype',
            name='fdc_id',
            field=models.CharField(blank=True, default=None, max_length=128, null=True),
        ),
    ]
