# Generated by Django 4.2.7 on 2023-11-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0204_propertytype_fdc_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='fdc_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='propertytype',
            name='fdc_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
