# Generated by Django 4.2.7 on 2023-12-30 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0205_alter_food_fdc_id_alter_propertytype_fdc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
