# Generated by Django 4.2.7 on 2023-12-24 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0205_alter_food_fdc_id_alter_propertytype_fdc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebook',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
