# Generated by Django 4.2.7 on 2024-01-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0206_alter_storage_path_homeassistantconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeassistantconfig',
            name='on_shopping_list_entry_created_enabled',
            field=models.BooleanField(default=False, help_text='Enable syncing ShoppingListEntry to Homeassistant Todo List'),
        ),
        migrations.AddField(
            model_name='homeassistantconfig',
            name='on_shopping_list_entry_deleted_enabled',
            field=models.BooleanField(default=False, help_text='Enable syncing ShoppingListEntry deletion to Homeassistant Todo List'),
        ),
        migrations.AddField(
            model_name='homeassistantconfig',
            name='on_shopping_list_entry_updated_enabled',
            field=models.BooleanField(default=False, help_text='PLACEHOLDER'),
        ),
        migrations.AlterField(
            model_name='homeassistantconfig',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
