# Generated by Django 4.2.7 on 2024-01-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0206_rename_sticky_navbar_userpreference_nav_sticky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglistentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
