# Generated by Django 4.2.7 on 2024-01-14 16:00

import cookbook.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbook', '0207_space_logo_color_128_space_logo_color_144_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeAssistantConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(1)])),
                ('enabled', models.BooleanField(default=True, help_text='Is Connector Enabled')),
                ('on_shopping_list_entry_created_enabled', models.BooleanField(default=False)),
                ('on_shopping_list_entry_updated_enabled', models.BooleanField(default=False)),
                ('on_shopping_list_entry_deleted_enabled', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True)),
                ('token', models.CharField(blank=True, max_length=512)),
                ('todo_entity', models.CharField(default='todo.shopping_list', max_length=128)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.space')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, cookbook.models.PermissionModelMixin),
        ),
        migrations.CreateModel(
            name='ExampleConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(1)])),
                ('enabled', models.BooleanField(default=True, help_text='Is Connector Enabled')),
                ('on_shopping_list_entry_created_enabled', models.BooleanField(default=False)),
                ('on_shopping_list_entry_updated_enabled', models.BooleanField(default=False)),
                ('on_shopping_list_entry_deleted_enabled', models.BooleanField(default=False)),
                ('feed_url', models.URLField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.space')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, cookbook.models.PermissionModelMixin),
        ),
    ]
