# Generated by Django 4.2.7 on 2024-02-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0210_shoppinglistentry_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipebook',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
