# Generated by Django 4.2.7 on 2024-02-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0211_recipebook_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_amount',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=32, null=True),
        ),
    ]
