# Generated by Django 4.2.10 on 2024-02-19 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "cookbook",
            "0213_remove_property_property_unique_import_food_per_space_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="ShoppingList",
        ),
    ]
