# Generated by Django 4.2.10 on 2024-02-26 14:41

import cookbook.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cookbook', '0214_cooklog_comment_cooklog_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectorConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(1)])),
                ('type', models.CharField(choices=[('HomeAssistant', 'HomeAssistant')], default='HomeAssistant', max_length=128)),
                ('enabled', models.BooleanField(default=True, help_text='Is Connector Enabled')),
                ('on_shopping_list_entry_created_enabled', models.BooleanField(default=False)),
                ('on_shopping_list_entry_updated_enabled', models.BooleanField(default=False)),
                ('on_shopping_list_entry_deleted_enabled', models.BooleanField(default=False)),
                ('url', models.URLField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=512, null=True)),
                ('todo_entity', models.CharField(blank=True, max_length=128, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.space')),
            ],
            bases=(models.Model, cookbook.models.PermissionModelMixin),
        ),
    ]
