# Generated by Django 4.2.15 on 2024-09-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0218_alter_mealplan_from_date_alter_mealplan_to_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorconfig',
            name='supports_description_field',
            field=models.BooleanField(default=True, help_text='Does the todo entity support the description field'),
        ),
    ]
