# Generated by Django 5.2.6 on 2025-09-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0001_squashed_0227_space_ai_default_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='space_setup_completed',
            field=models.BooleanField(default=True),
        ),
    ]
