# Generated by Django 5.2.6 on 2025-09-25 18:56

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension, UnaccentExtension

class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0229_alter_ailog_options_alter_aiprovider_options_and_more'),
    ]

    operations = [
        TrigramExtension(),
        UnaccentExtension(),
    ]
