# Generated by Django 5.2.6 on 2025-09-30 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0230_auto_20250925_2056'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aiprovider',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='automation',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='bookmarkletimport',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='connectorconfig',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='cooklog',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='customfilter',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='exportlog',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='importlog',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='invitelink',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='mealplan',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='mealtype',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='recipebook',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='recipeimport',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='sharelink',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='shoppinglistentry',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='shoppinglistrecipe',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='space',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='storage',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='supermarket',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='supermarketcategory',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='sync',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='synclog',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='telegrambot',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='unitconversion',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='userfile',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='userspace',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='viewlog',
            options={'ordering': ('pk',)},
        ),
    ]
