# Generated by Django 4.2 on 2025-01-01 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0234_alter_shoppinglist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='default_unit',
            field=models.ForeignKey(blank=True, help_text='Default unit for ingredients without a unit (used in property calculations)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='space_default_unit', to='cookbook.unit'),
        ),
    ]
