# Generated by Django 5.2.10 on 2026-02-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0236_inventorylocation_inventoryentry_inventorylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorylog',
            name='booking_type',
            field=models.CharField(choices=[('add', 'Add'), ('remove', 'Remove'), ('move', 'Move')], default='add', max_length=10),
        ),
    ]
