# Generated by Django 5.2.10 on 2026-02-28 19:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django_scopes import scopes_disabled

from cookbook.models import UserPreference


def apply_migration(apps, schema_editor):
    with scopes_disabled():
        MealType = apps.get_model('cookbook', 'MealType')
        Space = apps.get_model('cookbook', 'Space')

        delete_mealtype_ids = []
        update_userpreference_list = []

        for space in Space.objects.all():
            space_mealtypes = []
            for mt in MealType.objects.filter(space=space):
                replaced_by = None

                # check if another mealtype has the same name and if so delete the duplicate
                for sMt in space_mealtypes:
                    if mt.name.strip().lower() == sMt.name.strip().lower():
                        delete_mealtype_ids.append(mt.id)
                        replaced_by = sMt

                if not replaced_by:
                    space_mealtypes.append(mt)

                # migrate default to userpreference
                if mt.default:
                    if replaced_by:
                        mt.created_by.userpreference.default_meal_type_id = replaced_by.id
                    else:
                        mt.created_by.userpreference.default_meal_type_id = mt.id
                    update_userpreference_list.append(mt.created_by.userpreference)

        MealType.objects.filter(id__in=delete_mealtype_ids).delete()
        UserPreference.objects.bulk_update(update_userpreference_list, ['default_meal_type_id'], batch_size=500)




class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0236_household_userspace_household_inventorylocation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='default_meal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cookbook.mealtype'),
        ),
        migrations.RunPython(apply_migration),
        migrations.RemoveConstraint(
            model_name='mealtype',
            name='mt_unique_name_per_space',
        ),
        migrations.AddConstraint(
            model_name='mealtype',
            constraint=models.UniqueConstraint(fields=('space', 'name'), name='mt_unique_name_per_space'),
        ),
    ]
