# Generated by Django 5.2.11 on 2026-03-01 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0237_remove_mealtype_mt_unique_name_per_space_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealplan',
            name='shared',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='plan_share',
        ),
        migrations.RemoveField(
            model_name='userpreference',
            name='shopping_share',
        ),
    ]
