# Generated by Django 5.2.10 on 2026-02-08 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0237_inventorylog_booking_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryentry',
            old_name='storage_location',
            new_name='inventory_location',
        ),
    ]
