# Generated by Django 5.2.10 on 2026-03-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0237_remove_mealtype_mt_unique_name_per_space_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mealtype',
            name='mt_unique_name_per_space',
        ),
        migrations.AddConstraint(
            model_name='mealtype',
            constraint=models.UniqueConstraint(fields=('space', 'name'), name='mt_unique_name_per_space'),
        ),
    ]
