# Generated by Django 5.2.11 on 2026-03-01 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0238_remove_dead_sharing_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('pk',)},
        ),
        migrations.AlterModelOptions(
            name='recipebookentry',
            options={'ordering': ('pk',)},
        ),
    ]
