# Generated by Django 5.2.12 on 2026-03-21 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0240_remove_ingredient_always_use_plural_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitelink',
            name='household',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cookbook.household'),
        ),
    ]
