# Generated by Django 5.2.12 on 2026-04-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0241_invitelink_household'),
    ]

    operations = [
        migrations.AddField(
            model_name='space',
            name='household_setup_completed',
            field=models.BooleanField(default=False),
        ),
    ]
