# Generated by Django 5.2.13 on 2026-05-08 08:08

from django.db import migrations


def backfill_internal(apps, schema_editor):
    Recipe = apps.get_model('cookbook', 'Recipe')
    # Fetch IDs of recipes that are marked internal=False but have steps
    recipe_ids = list(Recipe.objects.filter(internal=False, steps__isnull=False).values_list('id', flat=True).distinct())
    if recipe_ids:
        Recipe.objects.filter(id__in=recipe_ids).update(internal=True)


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0242_space_household_setup_completed'),
    ]

    operations = [
        migrations.RunPython(backfill_internal, migrations.RunPython.noop),
    ]
