# Generated by Django 5.2.12 on 2026-07-06 00:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0242_space_household_setup_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='properties_consumed_fraction',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
