# Generated by Django 5.2.13 on 2026-06-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookbook", "0242_space_household_setup_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="shoppinglistentry",
            name="note",
            field=models.TextField(blank=True),
        ),
    ]
