# Generated by Django 5.2.13 on 2026-04-15 16:59

import cookbook.models
import django.db.models.deletion
import django_prometheus.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0243_userpreference_dark_theme_userpreference_light_theme'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeUserWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.recipe')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cookbook.space')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_weights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pk',),
                'indexes': [models.Index(fields=['id'], name='cookbook_re_id_955d11_idx'), models.Index(fields=['user'], name='cookbook_re_user_id_521e32_idx'), models.Index(fields=['recipe'], name='cookbook_re_recipe__257cdd_idx'), models.Index(fields=['user', 'recipe'], name='cookbook_re_user_id_64b64d_idx'), models.Index(fields=['weight'], name='cookbook_re_weight_b03bba_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'recipe'), name='unique_user_recipe_weight')],
            },
            bases=(django_prometheus.models.ExportModelOperationsMixin('recipe_user_weight'), models.Model, cookbook.models.PermissionModelMixin),
        ),
    ]
