kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: recipes
  name: recipes-nginx-config
data:
  nginx-config: |-
    events {
      worker_connections 1024;
    }
    http {
      server {
        listen 80;
        server_name _;

        client_max_body_size 16M;

        # serve static files
        location /static/ {
          alias /static/;
        }
        # serve media files
        location /media/ {
          alias /media/;
        }
        # pass requests for dynamic content to gunicorn
        location / {
          proxy_set_header Host $host;
          proxy_pass http://localhost:8080;
        }
      }
    }
