/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `add` - Add
 * * `remove` - Remove
 * * `move` - Move
 * @export
 */
export const BookingTypeEnum = {
    Add: 'add',
    Remove: 'remove',
    Move: 'move'
} as const;
export type BookingTypeEnum = typeof BookingTypeEnum[keyof typeof BookingTypeEnum];


export function instanceOfBookingTypeEnum(value: any): boolean {
    for (const key in BookingTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(BookingTypeEnum, key)) {
            if (BookingTypeEnum[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function BookingTypeEnumFromJSON(json: any): BookingTypeEnum {
    return BookingTypeEnumFromJSONTyped(json, false);
}

export function BookingTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): BookingTypeEnum {
    return json as BookingTypeEnum;
}

export function BookingTypeEnumToJSON(value?: BookingTypeEnum | null): any {
    return value as any;
}

