/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnterpriseKeyword
 */
export interface EnterpriseKeyword {
    /**
     * 
     * @type {number}
     * @memberof EnterpriseKeyword
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseKeyword
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseKeyword
     */
    readonly label: string;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseKeyword
     */
    description?: string;
}

/**
 * Check if a given object implements the EnterpriseKeyword interface.
 */
export function instanceOfEnterpriseKeyword(value: object): value is EnterpriseKeyword {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('label' in value) || value['label'] === undefined) return false;
    return true;
}

export function EnterpriseKeywordFromJSON(json: any): EnterpriseKeyword {
    return EnterpriseKeywordFromJSONTyped(json, false);
}

export function EnterpriseKeywordFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnterpriseKeyword {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'label': json['label'],
        'description': json['description'] == null ? undefined : json['description'],
    };
}

export function EnterpriseKeywordToJSON(value?: Omit<EnterpriseKeyword, 'label'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
    };
}

