/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlignmentEnum } from './AlignmentEnum';
import {
    AlignmentEnumFromJSON,
    AlignmentEnumFromJSONTyped,
    AlignmentEnumToJSON,
} from './AlignmentEnum';
import type { EnterpriseSocialEmbedTypeEnum } from './EnterpriseSocialEmbedTypeEnum';
import {
    EnterpriseSocialEmbedTypeEnumFromJSON,
    EnterpriseSocialEmbedTypeEnumFromJSONTyped,
    EnterpriseSocialEmbedTypeEnumToJSON,
} from './EnterpriseSocialEmbedTypeEnum';
import type { Keyword } from './Keyword';
import {
    KeywordFromJSON,
    KeywordFromJSONTyped,
    KeywordToJSON,
} from './Keyword';

/**
 * Adds nested create feature
 * @export
 * @interface EnterpriseSocialEmbed
 */
export interface EnterpriseSocialEmbed {
    /**
     * 
     * @type {number}
     * @memberof EnterpriseSocialEmbed
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseSocialEmbed
     */
    name: string;
    /**
     * 
     * @type {EnterpriseSocialEmbedTypeEnum}
     * @memberof EnterpriseSocialEmbed
     */
    type: EnterpriseSocialEmbedTypeEnum;
    /**
     * 
     * @type {Array<Keyword>}
     * @memberof EnterpriseSocialEmbed
     */
    keywords: Array<Keyword>;
    /**
     * 
     * @type {AlignmentEnum}
     * @memberof EnterpriseSocialEmbed
     */
    alignment?: AlignmentEnum;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseSocialEmbed
     */
    backgroundColor?: string;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseSocialEmbed
     */
    accentColor?: string;
    /**
     * 
     * @type {string}
     * @memberof EnterpriseSocialEmbed
     */
    uuid?: string;
}

/**
 * Check if a given object implements the EnterpriseSocialEmbed interface.
 */
export function instanceOfEnterpriseSocialEmbed(value: object): value is EnterpriseSocialEmbed {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('keywords' in value) || value['keywords'] === undefined) return false;
    return true;
}

export function EnterpriseSocialEmbedFromJSON(json: any): EnterpriseSocialEmbed {
    return EnterpriseSocialEmbedFromJSONTyped(json, false);
}

export function EnterpriseSocialEmbedFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnterpriseSocialEmbed {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'type': EnterpriseSocialEmbedTypeEnumFromJSON(json['type']),
        'keywords': ((json['keywords'] as Array<any>).map(KeywordFromJSON)),
        'alignment': json['alignment'] == null ? undefined : AlignmentEnumFromJSON(json['alignment']),
        'backgroundColor': json['background_color'] == null ? undefined : json['background_color'],
        'accentColor': json['accent_color'] == null ? undefined : json['accent_color'],
        'uuid': json['uuid'] == null ? undefined : json['uuid'],
    };
}

export function EnterpriseSocialEmbedToJSON(value?: EnterpriseSocialEmbed | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'type': EnterpriseSocialEmbedTypeEnumToJSON(value['type']),
        'keywords': ((value['keywords'] as Array<any>).map(KeywordToJSON)),
        'alignment': AlignmentEnumToJSON(value['alignment']),
        'background_color': value['backgroundColor'],
        'accent_color': value['accentColor'],
        'uuid': value['uuid'],
    };
}

