/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FoodInheritField } from './FoodInheritField';
import {
    FoodInheritFieldFromJSON,
    FoodInheritFieldFromJSONTyped,
    FoodInheritFieldToJSON,
} from './FoodInheritField';
import type { FoodSimple } from './FoodSimple';
import {
    FoodSimpleFromJSON,
    FoodSimpleFromJSONTyped,
    FoodSimpleToJSON,
} from './FoodSimple';
import type { Property } from './Property';
import {
    PropertyFromJSON,
    PropertyFromJSONTyped,
    PropertyToJSON,
} from './Property';
import type { RecipeSimple } from './RecipeSimple';
import {
    RecipeSimpleFromJSON,
    RecipeSimpleFromJSONTyped,
    RecipeSimpleToJSON,
} from './RecipeSimple';
import type { SupermarketCategory } from './SupermarketCategory';
import {
    SupermarketCategoryFromJSON,
    SupermarketCategoryFromJSONTyped,
    SupermarketCategoryToJSON,
} from './SupermarketCategory';
import type { Unit } from './Unit';
import {
    UnitFromJSON,
    UnitFromJSONTyped,
    UnitToJSON,
} from './Unit';

/**
 * Moves `UniqueValidator`'s from the validation stage to the save stage.
 * It solves the problem with nested validation for unique fields on update.
 * 
 * If you want more details, you can read related issues and articles:
 * https://github.com/beda-software/drf-writable-nested/issues/1
 * http://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers
 * 
 * Example of usage:
 * ```
 *     class Child(models.Model):
 *     field = models.CharField(unique=True)
 * 
 * 
 * class Parent(models.Model):
 *     child = models.ForeignKey('Child')
 * 
 * 
 * class ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):
 *     class Meta:
 *         model = Child
 * 
 * 
 * class ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):
 *     child = ChildSerializer()
 * 
 *     class Meta:
 *         model = Parent
 * ```
 * 
 * Note: `UniqueFieldsMixin` must be applied only on the serializer
 * which has unique fields.
 * 
 * Note: When you are using both mixins
 * (`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)
 * you should put `UniqueFieldsMixin` ahead.
 * @export
 * @interface Food
 */
export interface Food {
    /**
     * 
     * @type {number}
     * @memberof Food
     */
    readonly id: number;
    /**
     * 
     * @type {string}
     * @memberof Food
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof Food
     */
    pluralName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Food
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof Food
     */
    readonly shopping: string;
    /**
     * 
     * @type {RecipeSimple}
     * @memberof Food
     */
    recipe?: RecipeSimple | null;
    /**
     * 
     * @type {string}
     * @memberof Food
     */
    url?: string | null;
    /**
     * 
     * @type {Array<Property>}
     * @memberof Food
     */
    properties?: Array<Property> | null;
    /**
     * 
     * @type {string}
     * @memberof Food
     */
    propertiesFoodAmount?: string;
    /**
     * 
     * @type {Unit}
     * @memberof Food
     */
    propertiesFoodUnit?: Unit | null;
    /**
     * 
     * @type {number}
     * @memberof Food
     */
    fdcId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof Food
     */
    foodOnhand?: string | null;
    /**
     * 
     * @type {SupermarketCategory}
     * @memberof Food
     */
    supermarketCategory?: SupermarketCategory | null;
    /**
     * 
     * @type {string}
     * @memberof Food
     */
    readonly parent: string;
    /**
     * 
     * @type {number}
     * @memberof Food
     */
    readonly numchild: number;
    /**
     * 
     * @type {Array<FoodInheritField>}
     * @memberof Food
     */
    inheritFields?: Array<FoodInheritField> | null;
    /**
     * 
     * @type {string}
     * @memberof Food
     */
    readonly fullName: string;
    /**
     * 
     * @type {boolean}
     * @memberof Food
     */
    ignoreShopping?: boolean;
    /**
     * 
     * @type {Array<FoodSimple>}
     * @memberof Food
     */
    substitute?: Array<FoodSimple> | null;
    /**
     * 
     * @type {boolean}
     * @memberof Food
     */
    substituteSiblings?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof Food
     */
    substituteChildren?: boolean;
    /**
     * 
     * @type {string}
     * @memberof Food
     */
    readonly substituteOnhand: string;
    /**
     * 
     * @type {Array<FoodInheritField>}
     * @memberof Food
     */
    childInheritFields?: Array<FoodInheritField> | null;
    /**
     * 
     * @type {string}
     * @memberof Food
     */
    openDataSlug?: string | null;
}

/**
 * Check if a given object implements the Food interface.
 */
export function instanceOfFood(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "shopping" in value;
    isInstance = isInstance && "parent" in value;
    isInstance = isInstance && "numchild" in value;
    isInstance = isInstance && "fullName" in value;
    isInstance = isInstance && "substituteOnhand" in value;

    return isInstance;
}

export function FoodFromJSON(json: any): Food {
    return FoodFromJSONTyped(json, false);
}

export function FoodFromJSONTyped(json: any, ignoreDiscriminator: boolean): Food {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'pluralName': !exists(json, 'plural_name') ? undefined : json['plural_name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'shopping': json['shopping'],
        'recipe': !exists(json, 'recipe') ? undefined : RecipeSimpleFromJSON(json['recipe']),
        'url': !exists(json, 'url') ? undefined : json['url'],
        'properties': !exists(json, 'properties') ? undefined : (json['properties'] === null ? null : (json['properties'] as Array<any>).map(PropertyFromJSON)),
        'propertiesFoodAmount': !exists(json, 'properties_food_amount') ? undefined : json['properties_food_amount'],
        'propertiesFoodUnit': !exists(json, 'properties_food_unit') ? undefined : UnitFromJSON(json['properties_food_unit']),
        'fdcId': !exists(json, 'fdc_id') ? undefined : json['fdc_id'],
        'foodOnhand': !exists(json, 'food_onhand') ? undefined : json['food_onhand'],
        'supermarketCategory': !exists(json, 'supermarket_category') ? undefined : SupermarketCategoryFromJSON(json['supermarket_category']),
        'parent': json['parent'],
        'numchild': json['numchild'],
        'inheritFields': !exists(json, 'inherit_fields') ? undefined : (json['inherit_fields'] === null ? null : (json['inherit_fields'] as Array<any>).map(FoodInheritFieldFromJSON)),
        'fullName': json['full_name'],
        'ignoreShopping': !exists(json, 'ignore_shopping') ? undefined : json['ignore_shopping'],
        'substitute': !exists(json, 'substitute') ? undefined : (json['substitute'] === null ? null : (json['substitute'] as Array<any>).map(FoodSimpleFromJSON)),
        'substituteSiblings': !exists(json, 'substitute_siblings') ? undefined : json['substitute_siblings'],
        'substituteChildren': !exists(json, 'substitute_children') ? undefined : json['substitute_children'],
        'substituteOnhand': json['substitute_onhand'],
        'childInheritFields': !exists(json, 'child_inherit_fields') ? undefined : (json['child_inherit_fields'] === null ? null : (json['child_inherit_fields'] as Array<any>).map(FoodInheritFieldFromJSON)),
        'openDataSlug': !exists(json, 'open_data_slug') ? undefined : json['open_data_slug'],
    };
}

export function FoodToJSON(value?: Food | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'plural_name': value.pluralName,
        'description': value.description,
        'recipe': RecipeSimpleToJSON(value.recipe),
        'url': value.url,
        'properties': value.properties === undefined ? undefined : (value.properties === null ? null : (value.properties as Array<any>).map(PropertyToJSON)),
        'properties_food_amount': value.propertiesFoodAmount,
        'properties_food_unit': UnitToJSON(value.propertiesFoodUnit),
        'fdc_id': value.fdcId,
        'food_onhand': value.foodOnhand,
        'supermarket_category': SupermarketCategoryToJSON(value.supermarketCategory),
        'inherit_fields': value.inheritFields === undefined ? undefined : (value.inheritFields === null ? null : (value.inheritFields as Array<any>).map(FoodInheritFieldToJSON)),
        'ignore_shopping': value.ignoreShopping,
        'substitute': value.substitute === undefined ? undefined : (value.substitute === null ? null : (value.substitute as Array<any>).map(FoodSimpleToJSON)),
        'substitute_siblings': value.substituteSiblings,
        'substitute_children': value.substituteChildren,
        'child_inherit_fields': value.childInheritFields === undefined ? undefined : (value.childInheritFields === null ? null : (value.childInheritFields as Array<any>).map(FoodInheritFieldToJSON)),
        'open_data_slug': value.openDataSlug,
    };
}

