/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Moves `UniqueValidator`'s from the validation stage to the save stage.
 * It solves the problem with nested validation for unique fields on update.
 * 
 * If you want more details, you can read related issues and articles:
 * https://github.com/beda-software/drf-writable-nested/issues/1
 * http://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers
 * 
 * Example of usage:
 * ```
 *     class Child(models.Model):
 *     field = models.CharField(unique=True)
 * 
 * 
 * class Parent(models.Model):
 *     child = models.ForeignKey('Child')
 * 
 * 
 * class ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):
 *     class Meta:
 *         model = Child
 * 
 * 
 * class ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):
 *     child = ChildSerializer()
 * 
 *     class Meta:
 *         model = Parent
 * ```
 * 
 * Note: `UniqueFieldsMixin` must be applied only on the serializer
 * which has unique fields.
 * 
 * Note: When you are using both mixins
 * (`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)
 * you should put `UniqueFieldsMixin` ahead.
 * @export
 * @interface FoodInheritFieldRequest
 */
export interface FoodInheritFieldRequest {
    /**
     * 
     * @type {string}
     * @memberof FoodInheritFieldRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof FoodInheritFieldRequest
     */
    field?: string;
    /**
     * 
     * @type {number}
     * @memberof FoodInheritFieldRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the FoodInheritFieldRequest interface.
 */
export function instanceOfFoodInheritFieldRequest(value: object): boolean {
    return true;
}

export function FoodInheritFieldRequestFromJSON(json: any): FoodInheritFieldRequest {
    return FoodInheritFieldRequestFromJSONTyped(json, false);
}

export function FoodInheritFieldRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodInheritFieldRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'field': json['field'] == null ? undefined : json['field'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function FoodInheritFieldRequestToJSON(value?: FoodInheritFieldRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'field': value['field'],
        'id': value['id'],
    };
}

