/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ShoppingList } from './ShoppingList';
import {
    ShoppingListFromJSON,
    ShoppingListFromJSONTyped,
    ShoppingListToJSON,
} from './ShoppingList';
import type { SupermarketCategory } from './SupermarketCategory';
import {
    SupermarketCategoryFromJSON,
    SupermarketCategoryFromJSONTyped,
    SupermarketCategoryToJSON,
} from './SupermarketCategory';

/**
 * 
 * @export
 * @interface FoodShopping
 */
export interface FoodShopping {
    /**
     * 
     * @type {number}
     * @memberof FoodShopping
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof FoodShopping
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof FoodShopping
     */
    pluralName?: string;
    /**
     * 
     * @type {SupermarketCategory}
     * @memberof FoodShopping
     */
    readonly supermarketCategory: SupermarketCategory;
    /**
     * 
     * @type {ShoppingList}
     * @memberof FoodShopping
     */
    readonly shoppingLists: ShoppingList;
}

/**
 * Check if a given object implements the FoodShopping interface.
 */
export function instanceOfFoodShopping(value: object): value is FoodShopping {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('supermarketCategory' in value) || value['supermarketCategory'] === undefined) return false;
    if (!('shoppingLists' in value) || value['shoppingLists'] === undefined) return false;
    return true;
}

export function FoodShoppingFromJSON(json: any): FoodShopping {
    return FoodShoppingFromJSONTyped(json, false);
}

export function FoodShoppingFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodShopping {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'pluralName': json['plural_name'] == null ? undefined : json['plural_name'],
        'supermarketCategory': SupermarketCategoryFromJSON(json['supermarket_category']),
        'shoppingLists': ShoppingListFromJSON(json['shopping_lists']),
    };
}

export function FoodShoppingToJSON(value?: Omit<FoodShopping, 'supermarketCategory'|'shoppingLists'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'plural_name': value['pluralName'],
    };
}

