/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DeleteEnum } from './DeleteEnum';
import {
    DeleteEnumFromJSON,
    DeleteEnumFromJSONTyped,
    DeleteEnumToJSON,
} from './DeleteEnum';

/**
 * 
 * @export
 * @interface FoodShoppingUpdateRequest
 */
export interface FoodShoppingUpdateRequest {
    /**
     * Amount of food to add to the shopping list
     * @type {number}
     * @memberof FoodShoppingUpdateRequest
     */
    amount?: number;
    /**
     * ID of unit to use for the shopping list
     * @type {number}
     * @memberof FoodShoppingUpdateRequest
     */
    unit?: number;
    /**
     * When set to true will delete all food from active shopping lists.
     * 
     * * `true` - true
     * @type {DeleteEnum}
     * @memberof FoodShoppingUpdateRequest
     */
    _delete: DeleteEnum | null;
    /**
     * 
     * @type {number}
     * @memberof FoodShoppingUpdateRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the FoodShoppingUpdateRequest interface.
 */
export function instanceOfFoodShoppingUpdateRequest(value: object): boolean {
    if (!('_delete' in value)) return false;
    return true;
}

export function FoodShoppingUpdateRequestFromJSON(json: any): FoodShoppingUpdateRequest {
    return FoodShoppingUpdateRequestFromJSONTyped(json, false);
}

export function FoodShoppingUpdateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FoodShoppingUpdateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        '_delete': DeleteEnumFromJSON(json['delete']),
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function FoodShoppingUpdateRequestToJSON(value?: FoodShoppingUpdateRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'unit': value['unit'],
        'delete': DeleteEnumToJSON(value['_delete']),
        'id': value['id'],
    };
}

