/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportImage
 */
export interface ImportImage {
    /**
     * 
     * @type {string}
     * @memberof ImportImage
     */
    image: string;
}

/**
 * Check if a given object implements the ImportImage interface.
 */
export function instanceOfImportImage(value: object): value is ImportImage {
    if (!('image' in value) || value['image'] === undefined) return false;
    return true;
}

export function ImportImageFromJSON(json: any): ImportImage {
    return ImportImageFromJSONTyped(json, false);
}

export function ImportImageFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportImage {
    if (json == null) {
        return json;
    }
    return {
        
        'image': json['image'],
    };
}

export function ImportImageToJSON(value?: ImportImage | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'image': value['image'],
    };
}
// ----------------------------------------------------------------------
// Custom model functions added by custom openapi-generator template
// ----------------------------------------------------------------------
import {ApiApi, ApiImportImageListRequest, PaginatedImportImageList} from "@/openapi";

/**
 * query list endpoint using the provided request parameters
 */
export function list(requestParameters: ApiImportImageListRequest = {}): Promise<PaginatedImportImageList> {
    const api = new ApiApi()
    return api.apiImportImageList(requestParameters)
}
