/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImportOpenData
 */
export interface ImportOpenData {
    /**
     * 
     * @type {string}
     * @memberof ImportOpenData
     */
    selectedVersion: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ImportOpenData
     */
    selectedDatatypes: Array<string>;
    /**
     * 
     * @type {boolean}
     * @memberof ImportOpenData
     */
    updateExisting?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ImportOpenData
     */
    useMetric?: boolean;
}

/**
 * Check if a given object implements the ImportOpenData interface.
 */
export function instanceOfImportOpenData(value: object): value is ImportOpenData {
    if (!('selectedVersion' in value) || value['selectedVersion'] === undefined) return false;
    if (!('selectedDatatypes' in value) || value['selectedDatatypes'] === undefined) return false;
    return true;
}

export function ImportOpenDataFromJSON(json: any): ImportOpenData {
    return ImportOpenDataFromJSONTyped(json, false);
}

export function ImportOpenDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImportOpenData {
    if (json == null) {
        return json;
    }
    return {
        
        'selectedVersion': json['selected_version'],
        'selectedDatatypes': json['selected_datatypes'],
        'updateExisting': json['update_existing'] == null ? undefined : json['update_existing'],
        'useMetric': json['use_metric'] == null ? undefined : json['use_metric'],
    };
}

export function ImportOpenDataToJSON(value?: ImportOpenData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'selected_version': value['selectedVersion'],
        'selected_datatypes': value['selectedDatatypes'],
        'update_existing': value['updateExisting'],
        'use_metric': value['useMetric'],
    };
}

