/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BookingTypeEnum } from './BookingTypeEnum';
import {
    BookingTypeEnumFromJSON,
    BookingTypeEnumFromJSONTyped,
    BookingTypeEnumToJSON,
} from './BookingTypeEnum';

/**
 * 
 * @export
 * @interface InventoryLog
 */
export interface InventoryLog {
    /**
     * 
     * @type {number}
     * @memberof InventoryLog
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof InventoryLog
     */
    entry: number;
    /**
     * 
     * @type {BookingTypeEnum}
     * @memberof InventoryLog
     */
    bookingType?: BookingTypeEnum;
    /**
     * 
     * @type {number}
     * @memberof InventoryLog
     */
    oldAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof InventoryLog
     */
    newAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof InventoryLog
     */
    oldStorageLocation: number;
    /**
     * 
     * @type {number}
     * @memberof InventoryLog
     */
    newStorageLocation: number;
    /**
     * 
     * @type {string}
     * @memberof InventoryLog
     */
    note?: string;
    /**
     * 
     * @type {Date}
     * @memberof InventoryLog
     */
    readonly createdAt: Date;
}

/**
 * Check if a given object implements the InventoryLog interface.
 */
export function instanceOfInventoryLog(value: object): value is InventoryLog {
    if (!('entry' in value) || value['entry'] === undefined) return false;
    if (!('oldStorageLocation' in value) || value['oldStorageLocation'] === undefined) return false;
    if (!('newStorageLocation' in value) || value['newStorageLocation'] === undefined) return false;
    if (!('createdAt' in value) || value['createdAt'] === undefined) return false;
    return true;
}

export function InventoryLogFromJSON(json: any): InventoryLog {
    return InventoryLogFromJSONTyped(json, false);
}

export function InventoryLogFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryLog {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'entry': json['entry'],
        'bookingType': json['booking_type'] == null ? undefined : BookingTypeEnumFromJSON(json['booking_type']),
        'oldAmount': json['old_amount'] == null ? undefined : json['old_amount'],
        'newAmount': json['new_amount'] == null ? undefined : json['new_amount'],
        'oldStorageLocation': json['old_storage_location'],
        'newStorageLocation': json['new_storage_location'],
        'note': json['note'] == null ? undefined : json['note'],
        'createdAt': (new Date(json['created_at'])),
    };
}

export function InventoryLogToJSON(value?: Omit<InventoryLog, 'createdAt'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'entry': value['entry'],
        'booking_type': BookingTypeEnumToJSON(value['bookingType']),
        'old_amount': value['oldAmount'],
        'new_amount': value['newAmount'],
        'old_storage_location': value['oldStorageLocation'],
        'new_storage_location': value['newStorageLocation'],
        'note': value['note'],
    };
}

