/* tslint:disable */
/* eslint-disable */
/**
 * Django Recipes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Automation } from './Automation';
import {
    AutomationFromJSON,
    AutomationFromJSONTyped,
    AutomationToJSON,
} from './Automation';

/**
 * 
 * @export
 * @interface ListAutomations200Response
 */
export interface ListAutomations200Response {
    /**
     * 
     * @type {number}
     * @memberof ListAutomations200Response
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof ListAutomations200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListAutomations200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Automation>}
     * @memberof ListAutomations200Response
     */
    results?: Array<Automation>;
}

/**
 * Check if a given object implements the ListAutomations200Response interface.
 */
export function instanceOfListAutomations200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListAutomations200ResponseFromJSON(json: any): ListAutomations200Response {
    return ListAutomations200ResponseFromJSONTyped(json, false);
}

export function ListAutomations200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListAutomations200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(AutomationFromJSON)),
    };
}

export function ListAutomations200ResponseToJSON(value?: ListAutomations200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(AutomationToJSON)),
    };
}

