/* tslint:disable */
/* eslint-disable */
/**
 * Django Recipes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CookLog } from './CookLog';
import {
    CookLogFromJSON,
    CookLogFromJSONTyped,
    CookLogToJSON,
} from './CookLog';

/**
 * 
 * @export
 * @interface ListCookLogs200Response
 */
export interface ListCookLogs200Response {
    /**
     * 
     * @type {number}
     * @memberof ListCookLogs200Response
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof ListCookLogs200Response
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ListCookLogs200Response
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<CookLog>}
     * @memberof ListCookLogs200Response
     */
    results?: Array<CookLog>;
}

/**
 * Check if a given object implements the ListCookLogs200Response interface.
 */
export function instanceOfListCookLogs200Response(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ListCookLogs200ResponseFromJSON(json: any): ListCookLogs200Response {
    return ListCookLogs200ResponseFromJSONTyped(json, false);
}

export function ListCookLogs200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ListCookLogs200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(CookLogFromJSON)),
    };
}

export function ListCookLogs200ResponseToJSON(value?: ListCookLogs200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(CookLogToJSON)),
    };
}

