/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Adds nested create feature
 * @export
 * @interface MealType
 */
export interface MealType {
    /**
     * 
     * @type {number}
     * @memberof MealType
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MealType
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof MealType
     */
    order?: number;
    /**
     * 
     * @type {string}
     * @memberof MealType
     */
    time?: string;
    /**
     * 
     * @type {string}
     * @memberof MealType
     */
    color?: string;
    /**
     * 
     * @type {boolean}
     * @memberof MealType
     */
    _default?: boolean;
    /**
     * 
     * @type {number}
     * @memberof MealType
     */
    readonly createdBy: number;
}

/**
 * Check if a given object implements the MealType interface.
 */
export function instanceOfMealType(value: object): value is MealType {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('createdBy' in value) || value['createdBy'] === undefined) return false;
    return true;
}

export function MealTypeFromJSON(json: any): MealType {
    return MealTypeFromJSONTyped(json, false);
}

export function MealTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): MealType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
        'order': json['order'] == null ? undefined : json['order'],
        'time': json['time'] == null ? undefined : json['time'],
        'color': json['color'] == null ? undefined : json['color'],
        '_default': json['default'] == null ? undefined : json['default'],
        'createdBy': json['created_by'],
    };
}

export function MealTypeToJSON(value?: Omit<MealType, 'createdBy'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'order': value['order'],
        'time': value['time'],
        'color': value['color'],
        'default': value['_default'],
    };
}

