/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `WEIGHT` - weight
 * * `VOLUME` - volume
 * * `OTHER` - other
 * @export
 */
export const OpenDataUnitTypeEnum = {
    Weight: 'WEIGHT',
    Volume: 'VOLUME',
    Other: 'OTHER'
} as const;
export type OpenDataUnitTypeEnum = typeof OpenDataUnitTypeEnum[keyof typeof OpenDataUnitTypeEnum];


export function instanceOfOpenDataUnitTypeEnum(value: any): boolean {
    for (const key in OpenDataUnitTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(OpenDataUnitTypeEnum, key)) {
            if (OpenDataUnitTypeEnum[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function OpenDataUnitTypeEnumFromJSON(json: any): OpenDataUnitTypeEnum {
    return OpenDataUnitTypeEnumFromJSONTyped(json, false);
}

export function OpenDataUnitTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenDataUnitTypeEnum {
    return json as OpenDataUnitTypeEnum;
}

export function OpenDataUnitTypeEnumToJSON(value?: OpenDataUnitTypeEnum | null): any {
    return value as any;
}

