/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpenDataProperty } from './OpenDataProperty';
import {
    OpenDataPropertyFromJSON,
    OpenDataPropertyFromJSONTyped,
    OpenDataPropertyToJSON,
} from './OpenDataProperty';

/**
 * Adds nested create feature
 * @export
 * @interface OpenDataFoodProperty
 */
export interface OpenDataFoodProperty {
    /**
     * 
     * @type {number}
     * @memberof OpenDataFoodProperty
     */
    readonly id: number;
    /**
     * 
     * @type {OpenDataProperty}
     * @memberof OpenDataFoodProperty
     */
    property: OpenDataProperty;
    /**
     * 
     * @type {string}
     * @memberof OpenDataFoodProperty
     */
    propertyAmount: string;
}

/**
 * Check if a given object implements the OpenDataFoodProperty interface.
 */
export function instanceOfOpenDataFoodProperty(value: object): boolean {
    if (!('id' in value)) return false;
    if (!('property' in value)) return false;
    if (!('propertyAmount' in value)) return false;
    return true;
}

export function OpenDataFoodPropertyFromJSON(json: any): OpenDataFoodProperty {
    return OpenDataFoodPropertyFromJSONTyped(json, false);
}

export function OpenDataFoodPropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenDataFoodProperty {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'property': OpenDataPropertyFromJSON(json['property']),
        'propertyAmount': json['property_amount'],
    };
}

export function OpenDataFoodPropertyToJSON(value?: OpenDataFoodProperty | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'property': OpenDataPropertyToJSON(value['property']),
        'property_amount': value['propertyAmount'],
    };
}

