/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    OpenDataVersion,
    OpenDataVersionFromJSON,
    OpenDataVersionFromJSONTyped,
    OpenDataVersionToJSON,
} from './';

/**
 * Moves `UniqueValidator`'s from the validation stage to the save stage.
It solves the problem with nested validation for unique fields on update.

If you want more details, you can read related issues and articles:
https://github.com/beda-software/drf-writable-nested/issues/1
http://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers

Example of usage:
```
    class Child(models.Model):
    field = models.CharField(unique=True)


class Parent(models.Model):
    child = models.ForeignKey('Child')


class ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):
    class Meta:
        model = Child


class ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):
    child = ChildSerializer()

    class Meta:
        model = Parent
```

Note: `UniqueFieldsMixin` must be applied only on the serializer
which has unique fields.

Note: When you are using both mixins
(`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)
you should put `UniqueFieldsMixin` ahead.
 * @export
 * @interface OpenDataProperty
 */
export interface OpenDataProperty {
    /**
     * 
     * @type {number}
     * @memberof OpenDataProperty
     */
    readonly id: number;
    /**
     * 
     * @type {OpenDataVersion}
     * @memberof OpenDataProperty
     */
    version: OpenDataVersion;
    /**
     * 
     * @type {string}
     * @memberof OpenDataProperty
     */
    slug: string;
    /**
     * 
     * @type {string}
     * @memberof OpenDataProperty
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof OpenDataProperty
     */
    unit?: string;
    /**
     * 
     * @type {number}
     * @memberof OpenDataProperty
     */
    fdcId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof OpenDataProperty
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof OpenDataProperty
     */
    readonly createdBy: string;
}

export function OpenDataPropertyFromJSON(json: any): OpenDataProperty {
    return OpenDataPropertyFromJSONTyped(json, false);
}

export function OpenDataPropertyFromJSONTyped(json: any, ignoreDiscriminator: boolean): OpenDataProperty {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'version': OpenDataVersionFromJSON(json['version']),
        'slug': json['slug'],
        'name': json['name'],
        'unit': !exists(json, 'unit') ? undefined : json['unit'],
        'fdcId': !exists(json, 'fdc_id') ? undefined : json['fdc_id'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
        'createdBy': json['created_by'],
    };
}

export function OpenDataPropertyToJSON(value?: OpenDataProperty | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': OpenDataVersionToJSON(value.version),
        'slug': value.slug,
        'name': value.name,
        'unit': value.unit,
        'fdc_id': value.fdcId,
        'comment': value.comment,
    };
}


