/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpenDataFood } from './OpenDataFood';
import {
    OpenDataFoodFromJSON,
    OpenDataFoodFromJSONTyped,
    OpenDataFoodToJSON,
} from './OpenDataFood';

/**
 * 
 * @export
 * @interface PaginatedOpenDataFoodList
 */
export interface PaginatedOpenDataFoodList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedOpenDataFoodList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedOpenDataFoodList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedOpenDataFoodList
     */
    previous?: string;
    /**
     * 
     * @type {Array<OpenDataFood>}
     * @memberof PaginatedOpenDataFoodList
     */
    results: Array<OpenDataFood>;
    /**
     * 
     * @type {Date}
     * @memberof PaginatedOpenDataFoodList
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the PaginatedOpenDataFoodList interface.
 */
export function instanceOfPaginatedOpenDataFoodList(value: object): value is PaginatedOpenDataFoodList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedOpenDataFoodListFromJSON(json: any): PaginatedOpenDataFoodList {
    return PaginatedOpenDataFoodListFromJSONTyped(json, false);
}

export function PaginatedOpenDataFoodListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedOpenDataFoodList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(OpenDataFoodFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function PaginatedOpenDataFoodListToJSON(value?: PaginatedOpenDataFoodList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(OpenDataFoodToJSON)),
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
    };
}

