/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Sync } from './Sync';
import {
    SyncFromJSON,
    SyncFromJSONTyped,
    SyncToJSON,
} from './Sync';

/**
 * 
 * @export
 * @interface PaginatedSyncList
 */
export interface PaginatedSyncList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedSyncList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSyncList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSyncList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Sync>}
     * @memberof PaginatedSyncList
     */
    results: Array<Sync>;
}

/**
 * Check if a given object implements the PaginatedSyncList interface.
 */
export function instanceOfPaginatedSyncList(value: object): value is PaginatedSyncList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedSyncListFromJSON(json: any): PaginatedSyncList {
    return PaginatedSyncListFromJSONTyped(json, false);
}

export function PaginatedSyncListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSyncList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(SyncFromJSON)),
    };
}

export function PaginatedSyncListToJSON(value?: PaginatedSyncList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(SyncToJSON)),
    };
}
// ----------------------------------------------------------------------
// Custom model functions added by custom openapi-generator template
// ----------------------------------------------------------------------
import {ApiApi, ApiPaginatedSyncListListRequest, PaginatedPaginatedSyncListList} from "@/openapi";

/**
 * query list endpoint using the provided request parameters
 */
export function list(requestParameters: ApiPaginatedSyncListListRequest = {}): Promise<PaginatedPaginatedSyncListList> {
    const api = new ApiApi()
    return api.apiPaginatedSyncListList(requestParameters)
}
