/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EnterpriseSocialRecipeSearch } from './EnterpriseSocialRecipeSearch';
import {
    EnterpriseSocialRecipeSearchFromJSON,
    EnterpriseSocialRecipeSearchFromJSONTyped,
    EnterpriseSocialRecipeSearchToJSON,
} from './EnterpriseSocialRecipeSearch';

/**
 * 
 * @export
 * @interface PaginatedEnterpriseSocialRecipeSearchList
 */
export interface PaginatedEnterpriseSocialRecipeSearchList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedEnterpriseSocialRecipeSearchList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedEnterpriseSocialRecipeSearchList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedEnterpriseSocialRecipeSearchList
     */
    previous?: string;
    /**
     * 
     * @type {Array<EnterpriseSocialRecipeSearch>}
     * @memberof PaginatedEnterpriseSocialRecipeSearchList
     */
    results: Array<EnterpriseSocialRecipeSearch>;
    /**
     * 
     * @type {Date}
     * @memberof PaginatedEnterpriseSocialRecipeSearchList
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the PaginatedEnterpriseSocialRecipeSearchList interface.
 */
export function instanceOfPaginatedEnterpriseSocialRecipeSearchList(value: object): value is PaginatedEnterpriseSocialRecipeSearchList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedEnterpriseSocialRecipeSearchListFromJSON(json: any): PaginatedEnterpriseSocialRecipeSearchList {
    return PaginatedEnterpriseSocialRecipeSearchListFromJSONTyped(json, false);
}

export function PaginatedEnterpriseSocialRecipeSearchListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedEnterpriseSocialRecipeSearchList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(EnterpriseSocialRecipeSearchFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function PaginatedEnterpriseSocialRecipeSearchListToJSON(value?: PaginatedEnterpriseSocialRecipeSearchList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(EnterpriseSocialRecipeSearchToJSON)),
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
    };
}

