/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeBookEntry } from './RecipeBookEntry';
import {
    RecipeBookEntryFromJSON,
    RecipeBookEntryFromJSONTyped,
    RecipeBookEntryToJSON,
} from './RecipeBookEntry';

/**
 * 
 * @export
 * @interface PaginatedRecipeBookEntryList
 */
export interface PaginatedRecipeBookEntryList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedRecipeBookEntryList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRecipeBookEntryList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRecipeBookEntryList
     */
    previous?: string;
    /**
     * 
     * @type {Array<RecipeBookEntry>}
     * @memberof PaginatedRecipeBookEntryList
     */
    results: Array<RecipeBookEntry>;
    /**
     * 
     * @type {Date}
     * @memberof PaginatedRecipeBookEntryList
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the PaginatedRecipeBookEntryList interface.
 */
export function instanceOfPaginatedRecipeBookEntryList(value: object): value is PaginatedRecipeBookEntryList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedRecipeBookEntryListFromJSON(json: any): PaginatedRecipeBookEntryList {
    return PaginatedRecipeBookEntryListFromJSONTyped(json, false);
}

export function PaginatedRecipeBookEntryListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedRecipeBookEntryList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(RecipeBookEntryFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function PaginatedRecipeBookEntryListToJSON(value?: PaginatedRecipeBookEntryList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(RecipeBookEntryToJSON)),
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
    };
}

