/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { RecipeSimple } from './RecipeSimple';
import {
    RecipeSimpleFromJSON,
    RecipeSimpleFromJSONTyped,
    RecipeSimpleToJSON,
    RecipeSimpleToJSONTyped,
} from './RecipeSimple';

/**
 * 
 * @export
 * @interface PaginatedRecipeSimpleList
 */
export interface PaginatedRecipeSimpleList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedRecipeSimpleList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRecipeSimpleList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedRecipeSimpleList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<RecipeSimple>}
     * @memberof PaginatedRecipeSimpleList
     */
    results: Array<RecipeSimple>;
}

/**
 * Check if a given object implements the PaginatedRecipeSimpleList interface.
 */
export function instanceOfPaginatedRecipeSimpleList(value: object): value is PaginatedRecipeSimpleList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedRecipeSimpleListFromJSON(json: any): PaginatedRecipeSimpleList {
    return PaginatedRecipeSimpleListFromJSONTyped(json, false);
}

export function PaginatedRecipeSimpleListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedRecipeSimpleList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(RecipeSimpleFromJSON)),
    };
}

export function PaginatedRecipeSimpleListToJSON(json: any): PaginatedRecipeSimpleList {
    return PaginatedRecipeSimpleListToJSONTyped(json, false);
}

export function PaginatedRecipeSimpleListToJSONTyped(value?: PaginatedRecipeSimpleList | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(RecipeSimpleToJSON)),
    };
}

