/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Household } from './Household';
import {
    HouseholdFromJSON,
    HouseholdFromJSONTyped,
    HouseholdToJSON,
} from './Household';

/**
 * 
 * @export
 * @interface PaginatedHouseholdList
 */
export interface PaginatedHouseholdList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedHouseholdList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedHouseholdList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedHouseholdList
     */
    previous?: string;
    /**
     * 
     * @type {Array<Household>}
     * @memberof PaginatedHouseholdList
     */
    results: Array<Household>;
    /**
     * 
     * @type {Date}
     * @memberof PaginatedHouseholdList
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the PaginatedHouseholdList interface.
 */
export function instanceOfPaginatedHouseholdList(value: object): value is PaginatedHouseholdList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedHouseholdListFromJSON(json: any): PaginatedHouseholdList {
    return PaginatedHouseholdListFromJSONTyped(json, false);
}

export function PaginatedHouseholdListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedHouseholdList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(HouseholdFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function PaginatedHouseholdListToJSON(value?: PaginatedHouseholdList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(HouseholdToJSON)),
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
    };
}

