/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ViewLog } from './ViewLog';
import {
    ViewLogFromJSON,
    ViewLogFromJSONTyped,
    ViewLogToJSON,
} from './ViewLog';

/**
 * 
 * @export
 * @interface PaginatedViewLogList
 */
export interface PaginatedViewLogList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedViewLogList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedViewLogList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedViewLogList
     */
    previous?: string;
    /**
     * 
     * @type {Array<ViewLog>}
     * @memberof PaginatedViewLogList
     */
    results?: Array<ViewLog>;
}

/**
 * Check if a given object implements the PaginatedViewLogList interface.
 */
export function instanceOfPaginatedViewLogList(value: object): boolean {
    return true;
}

export function PaginatedViewLogListFromJSON(json: any): PaginatedViewLogList {
    return PaginatedViewLogListFromJSONTyped(json, false);
}

export function PaginatedViewLogListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedViewLogList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(ViewLogFromJSON)),
    };
}

export function PaginatedViewLogListToJSON(value?: PaginatedViewLogList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(ViewLogToJSON)),
    };
}

