/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UnitConversion } from './UnitConversion';
import {
    UnitConversionFromJSON,
    UnitConversionFromJSONTyped,
    UnitConversionToJSON,
} from './UnitConversion';

/**
 * 
 * @export
 * @interface PaginatedUnitConversionList
 */
export interface PaginatedUnitConversionList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedUnitConversionList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedUnitConversionList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedUnitConversionList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<UnitConversion>}
     * @memberof PaginatedUnitConversionList
     */
    results: Array<UnitConversion>;
}

/**
 * Check if a given object implements the PaginatedUnitConversionList interface.
 */
export function instanceOfPaginatedUnitConversionList(value: object): value is PaginatedUnitConversionList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedUnitConversionListFromJSON(json: any): PaginatedUnitConversionList {
    return PaginatedUnitConversionListFromJSONTyped(json, false);
}

export function PaginatedUnitConversionListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedUnitConversionList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(UnitConversionFromJSON)),
    };
}

export function PaginatedUnitConversionListToJSON(value?: PaginatedUnitConversionList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(UnitConversionToJSON)),
    };
}
// ----------------------------------------------------------------------
// Custom model functions added by custom openapi-generator template
// ----------------------------------------------------------------------
import {ApiApi, ApiPaginatedUnitConversionListListRequest, PaginatedPaginatedUnitConversionListList} from "@/openapi";

/**
 * query list endpoint using the provided request parameters
 */
export function list(requestParameters: ApiPaginatedUnitConversionListListRequest = {}): Promise<PaginatedPaginatedUnitConversionListList> {
    const api = new ApiApi()
    return api.apiPaginatedUnitConversionListList(requestParameters)
}
