/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CookLog } from './CookLog';
import {
    CookLogFromJSON,
    CookLogFromJSONTyped,
    CookLogToJSON,
} from './CookLog';

/**
 * 
 * @export
 * @interface PaginatedCookLogList
 */
export interface PaginatedCookLogList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedCookLogList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCookLogList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCookLogList
     */
    previous?: string;
    /**
     * 
     * @type {Array<CookLog>}
     * @memberof PaginatedCookLogList
     */
    results?: Array<CookLog>;
}

/**
 * Check if a given object implements the PaginatedCookLogList interface.
 */
export function instanceOfPaginatedCookLogList(value: object): boolean {
    return true;
}

export function PaginatedCookLogListFromJSON(json: any): PaginatedCookLogList {
    return PaginatedCookLogListFromJSONTyped(json, false);
}

export function PaginatedCookLogListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCookLogList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'] == null ? undefined : json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': json['results'] == null ? undefined : ((json['results'] as Array<any>).map(CookLogFromJSON)),
    };
}

export function PaginatedCookLogListToJSON(value?: PaginatedCookLogList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': value['results'] == null ? undefined : ((value['results'] as Array<any>).map(CookLogToJSON)),
    };
}

