/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SyncLog } from './SyncLog';
import {
    SyncLogFromJSON,
    SyncLogFromJSONTyped,
    SyncLogToJSON,
} from './SyncLog';

/**
 * 
 * @export
 * @interface PaginatedSyncLogList
 */
export interface PaginatedSyncLogList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedSyncLogList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSyncLogList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSyncLogList
     */
    previous?: string;
    /**
     * 
     * @type {Array<SyncLog>}
     * @memberof PaginatedSyncLogList
     */
    results: Array<SyncLog>;
    /**
     * 
     * @type {Date}
     * @memberof PaginatedSyncLogList
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the PaginatedSyncLogList interface.
 */
export function instanceOfPaginatedSyncLogList(value: object): value is PaginatedSyncLogList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedSyncLogListFromJSON(json: any): PaginatedSyncLogList {
    return PaginatedSyncLogListFromJSONTyped(json, false);
}

export function PaginatedSyncLogListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSyncLogList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(SyncLogFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function PaginatedSyncLogListToJSON(value?: PaginatedSyncLogList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(SyncLogToJSON)),
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
    };
}

