/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InventoryLog } from './InventoryLog';
import {
    InventoryLogFromJSON,
    InventoryLogFromJSONTyped,
    InventoryLogToJSON,
} from './InventoryLog';

/**
 * 
 * @export
 * @interface PaginatedInventoryLogList
 */
export interface PaginatedInventoryLogList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedInventoryLogList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedInventoryLogList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedInventoryLogList
     */
    previous?: string;
    /**
     * 
     * @type {Array<InventoryLog>}
     * @memberof PaginatedInventoryLogList
     */
    results: Array<InventoryLog>;
    /**
     * 
     * @type {Date}
     * @memberof PaginatedInventoryLogList
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the PaginatedInventoryLogList interface.
 */
export function instanceOfPaginatedInventoryLogList(value: object): value is PaginatedInventoryLogList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedInventoryLogListFromJSON(json: any): PaginatedInventoryLogList {
    return PaginatedInventoryLogListFromJSONTyped(json, false);
}

export function PaginatedInventoryLogListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedInventoryLogList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(InventoryLogFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function PaginatedInventoryLogListToJSON(value?: PaginatedInventoryLogList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(InventoryLogToJSON)),
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
    };
}

