/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StorageLocation } from './StorageLocation';
import {
    StorageLocationFromJSON,
    StorageLocationFromJSONTyped,
    StorageLocationToJSON,
} from './StorageLocation';

/**
 * 
 * @export
 * @interface PaginatedStorageLocationList
 */
export interface PaginatedStorageLocationList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedStorageLocationList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedStorageLocationList
     */
    next?: string;
    /**
     * 
     * @type {string}
     * @memberof PaginatedStorageLocationList
     */
    previous?: string;
    /**
     * 
     * @type {Array<StorageLocation>}
     * @memberof PaginatedStorageLocationList
     */
    results: Array<StorageLocation>;
    /**
     * 
     * @type {Date}
     * @memberof PaginatedStorageLocationList
     */
    timestamp?: Date;
}

/**
 * Check if a given object implements the PaginatedStorageLocationList interface.
 */
export function instanceOfPaginatedStorageLocationList(value: object): value is PaginatedStorageLocationList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedStorageLocationListFromJSON(json: any): PaginatedStorageLocationList {
    return PaginatedStorageLocationListFromJSONTyped(json, false);
}

export function PaginatedStorageLocationListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedStorageLocationList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(StorageLocationFromJSON)),
        'timestamp': json['timestamp'] == null ? undefined : (new Date(json['timestamp'])),
    };
}

export function PaginatedStorageLocationListToJSON(value?: PaginatedStorageLocationList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(StorageLocationToJSON)),
        'timestamp': value['timestamp'] == null ? undefined : ((value['timestamp']).toISOString()),
    };
}

