/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedBookmarkletImportRequest
 */
export interface PatchedBookmarkletImportRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedBookmarkletImportRequest
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedBookmarkletImportRequest
     */
    html?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedBookmarkletImportRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the PatchedBookmarkletImportRequest interface.
 */
export function instanceOfPatchedBookmarkletImportRequest(value: object): boolean {
    return true;
}

export function PatchedBookmarkletImportRequestFromJSON(json: any): PatchedBookmarkletImportRequest {
    return PatchedBookmarkletImportRequestFromJSONTyped(json, false);
}

export function PatchedBookmarkletImportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedBookmarkletImportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
        'html': json['html'] == null ? undefined : json['html'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function PatchedBookmarkletImportRequestToJSON(value?: PatchedBookmarkletImportRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'url': value['url'],
        'html': value['html'],
        'id': value['id'],
    };
}

