/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Moves `UniqueValidator`'s from the validation stage to the save stage.
 * It solves the problem with nested validation for unique fields on update.
 * 
 * If you want more details, you can read related issues and articles:
 * https://github.com/beda-software/drf-writable-nested/issues/1
 * http://www.django-rest-framework.org/api-guide/validators/#updating-nested-serializers
 * 
 * Example of usage:
 * ```
 *     class Child(models.Model):
 *     field = models.CharField(unique=True)
 * 
 * 
 * class Parent(models.Model):
 *     child = models.ForeignKey('Child')
 * 
 * 
 * class ChildSerializer(UniqueFieldsMixin, serializers.ModelSerializer):
 *     class Meta:
 *         model = Child
 * 
 * 
 * class ParentSerializer(NestedUpdateMixin, serializers.ModelSerializer):
 *     child = ChildSerializer()
 * 
 *     class Meta:
 *         model = Parent
 * ```
 * 
 * Note: `UniqueFieldsMixin` must be applied only on the serializer
 * which has unique fields.
 * 
 * Note: When you are using both mixins
 * (`UniqueFieldsMixin` and `NestedCreateMixin` or `NestedUpdateMixin`)
 * you should put `UniqueFieldsMixin` ahead.
 * @export
 * @interface PatchedUnit
 */
export interface PatchedUnit {
    /**
     * 
     * @type {number}
     * @memberof PatchedUnit
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedUnit
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedUnit
     */
    pluralName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUnit
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUnit
     */
    baseUnit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PatchedUnit
     */
    openDataSlug?: string | null;
}

/**
 * Check if a given object implements the PatchedUnit interface.
 */
export function instanceOfPatchedUnit(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PatchedUnitFromJSON(json: any): PatchedUnit {
    return PatchedUnitFromJSONTyped(json, false);
}

export function PatchedUnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedUnit {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'pluralName': !exists(json, 'plural_name') ? undefined : json['plural_name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'baseUnit': !exists(json, 'base_unit') ? undefined : json['base_unit'],
        'openDataSlug': !exists(json, 'open_data_slug') ? undefined : json['open_data_slug'],
    };
}

export function PatchedUnitToJSON(value?: PatchedUnit | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'plural_name': value.pluralName,
        'description': value.description,
        'base_unit': value.baseUnit,
        'open_data_slug': value.openDataSlug,
    };
}

