/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface PatchedRecipeUserWeight
 */
export interface PatchedRecipeUserWeight {
    /**
     *
     * @type {number}
     * @memberof PatchedRecipeUserWeight
     */
    id?: number;
    /**
     *
     * @type {number}
     * @memberof PatchedRecipeUserWeight
     */
    recipe?: number;
    /**
     *
     * @type {number}
     * @memberof PatchedRecipeUserWeight
     */
    user?: number;
    /**
     *
     * @type {number}
     * @memberof PatchedRecipeUserWeight
     */
    weight?: number;
}

/**
 * Check if a given object implements the PatchedRecipeUserWeight interface.
 */
export function instanceOfPatchedRecipeUserWeight(value: object): value is PatchedRecipeUserWeight {
    return true;
}

export function PatchedRecipeUserWeightFromJSON(json: any): PatchedRecipeUserWeight {
    return PatchedRecipeUserWeightFromJSONTyped(json, false);
}

export function PatchedRecipeUserWeightFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedRecipeUserWeight {
    if (json == null) {
        return json;
    }
    return {

        'id': json['id'] == null ? undefined : json['id'],
        'recipe': json['recipe'] == null ? undefined : json['recipe'],
        'user': json['user'] == null ? undefined : json['user'],
        'weight': json['weight'] == null ? undefined : json['weight'],
    };
}

export function PatchedRecipeUserWeightToJSON(value?: Omit<PatchedRecipeUserWeight, 'createdAt'|'updatedAt'> | null): any {
    if (value == null) {
        return value;
    }
    return {

        'id': value['id'],
        'recipe': value['recipe'],
        'user': value['user'],
        'weight': value['weight'],
    };
}

