/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedStorageEntry
 */
export interface PatchedStorageEntry {
    /**
     * 
     * @type {number}
     * @memberof PatchedStorageEntry
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedStorageEntry
     */
    storageLocation?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedStorageEntry
     */
    subLocation?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedStorageEntry
     */
    code?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedStorageEntry
     */
    food?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedStorageEntry
     */
    unit?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedStorageEntry
     */
    amount?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedStorageEntry
     */
    expires?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedStorageEntry
     */
    expiresFrozen?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedStorageEntry
     */
    note?: string;
}

/**
 * Check if a given object implements the PatchedStorageEntry interface.
 */
export function instanceOfPatchedStorageEntry(value: object): value is PatchedStorageEntry {
    return true;
}

export function PatchedStorageEntryFromJSON(json: any): PatchedStorageEntry {
    return PatchedStorageEntryFromJSONTyped(json, false);
}

export function PatchedStorageEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedStorageEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'storageLocation': json['storage_location'] == null ? undefined : json['storage_location'],
        'subLocation': json['sub_location'] == null ? undefined : json['sub_location'],
        'code': json['code'] == null ? undefined : json['code'],
        'food': json['food'] == null ? undefined : json['food'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'amount': json['amount'] == null ? undefined : json['amount'],
        'expires': json['expires'] == null ? undefined : (new Date(json['expires'])),
        'expiresFrozen': json['expires_frozen'] == null ? undefined : (new Date(json['expires_frozen'])),
        'note': json['note'] == null ? undefined : json['note'],
    };
}

export function PatchedStorageEntryToJSON(value?: PatchedStorageEntry | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'storage_location': value['storageLocation'],
        'sub_location': value['subLocation'],
        'code': value['code'],
        'food': value['food'],
        'unit': value['unit'],
        'amount': value['amount'],
        'expires': value['expires'] == null ? undefined : ((value['expires'] as any).toISOString().substring(0,10)),
        'expires_frozen': value['expiresFrozen'] == null ? undefined : ((value['expiresFrozen'] as any).toISOString().substring(0,10)),
        'note': value['note'],
    };
}

