/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Adds nested create feature
 * @export
 * @interface PatchedShoppingList
 */
export interface PatchedShoppingList {
    /**
     * 
     * @type {number}
     * @memberof PatchedShoppingList
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedShoppingList
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedShoppingList
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedShoppingList
     */
    color?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedShoppingList
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedShoppingList
     */
    readonly updatedAt?: Date;
}

/**
 * Check if a given object implements the PatchedShoppingList interface.
 */
export function instanceOfPatchedShoppingList(value: object): value is PatchedShoppingList {
    return true;
}

export function PatchedShoppingListFromJSON(json: any): PatchedShoppingList {
    return PatchedShoppingListFromJSONTyped(json, false);
}

export function PatchedShoppingListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedShoppingList {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'color': json['color'] == null ? undefined : json['color'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function PatchedShoppingListToJSON(value?: Omit<PatchedShoppingList, 'createdAt'|'updatedAt'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'color': value['color'],
    };
}

