/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedShoppingListRecipeRequest
 */
export interface PatchedShoppingListRecipeRequest {
    /**
     * 
     * @type {number}
     * @memberof PatchedShoppingListRecipeRequest
     */
    recipe?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedShoppingListRecipeRequest
     */
    mealplan?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedShoppingListRecipeRequest
     */
    servings?: number;
    /**
     * 
     * @type {number}
     * @memberof PatchedShoppingListRecipeRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the PatchedShoppingListRecipeRequest interface.
 */
export function instanceOfPatchedShoppingListRecipeRequest(value: object): boolean {
    return true;
}

export function PatchedShoppingListRecipeRequestFromJSON(json: any): PatchedShoppingListRecipeRequest {
    return PatchedShoppingListRecipeRequestFromJSONTyped(json, false);
}

export function PatchedShoppingListRecipeRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedShoppingListRecipeRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'recipe': json['recipe'] == null ? undefined : json['recipe'],
        'mealplan': json['mealplan'] == null ? undefined : json['mealplan'],
        'servings': json['servings'] == null ? undefined : json['servings'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function PatchedShoppingListRecipeRequestToJSON(value?: PatchedShoppingListRecipeRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'recipe': value['recipe'],
        'mealplan': value['mealplan'],
        'servings': value['servings'],
        'id': value['id'],
    };
}

