/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedAccessTokenRequest
 */
export interface PatchedAccessTokenRequest {
    /**
     * 
     * @type {Date}
     * @memberof PatchedAccessTokenRequest
     */
    expires?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedAccessTokenRequest
     */
    scope?: string;
    /**
     * 
     * @type {number}
     * @memberof PatchedAccessTokenRequest
     */
    id?: number;
}

/**
 * Check if a given object implements the PatchedAccessTokenRequest interface.
 */
export function instanceOfPatchedAccessTokenRequest(value: object): boolean {
    return true;
}

export function PatchedAccessTokenRequestFromJSON(json: any): PatchedAccessTokenRequest {
    return PatchedAccessTokenRequestFromJSONTyped(json, false);
}

export function PatchedAccessTokenRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedAccessTokenRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'expires': json['expires'] == null ? undefined : (new Date(json['expires'])),
        'scope': json['scope'] == null ? undefined : json['scope'],
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function PatchedAccessTokenRequestToJSON(value?: PatchedAccessTokenRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'expires': value['expires'] == null ? undefined : ((value['expires']).toISOString()),
        'scope': value['scope'],
        'id': value['id'],
    };
}

