/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatchedAiProvider
 */
export interface PatchedAiProvider {
    /**
     * 
     * @type {number}
     * @memberof PatchedAiProvider
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof PatchedAiProvider
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAiProvider
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAiProvider
     */
    apiKey?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAiProvider
     */
    modelName?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedAiProvider
     */
    url?: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatchedAiProvider
     */
    logCreditCost?: boolean;
    /**
     * 
     * @type {number}
     * @memberof PatchedAiProvider
     */
    space?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedAiProvider
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PatchedAiProvider
     */
    readonly updatedAt?: Date;
}

/**
 * Check if a given object implements the PatchedAiProvider interface.
 */
export function instanceOfPatchedAiProvider(value: object): value is PatchedAiProvider {
    return true;
}

export function PatchedAiProviderFromJSON(json: any): PatchedAiProvider {
    return PatchedAiProviderFromJSONTyped(json, false);
}

export function PatchedAiProviderFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedAiProvider {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'apiKey': json['api_key'] == null ? undefined : json['api_key'],
        'modelName': json['model_name'] == null ? undefined : json['model_name'],
        'url': json['url'] == null ? undefined : json['url'],
        'logCreditCost': json['log_credit_cost'] == null ? undefined : json['log_credit_cost'],
        'space': json['space'] == null ? undefined : json['space'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'updatedAt': json['updated_at'] == null ? undefined : (new Date(json['updated_at'])),
    };
}

export function PatchedAiProviderToJSON(value?: Omit<PatchedAiProvider, 'createdAt'|'updatedAt'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'api_key': value['apiKey'],
        'model_name': value['modelName'],
        'url': value['url'],
        'log_credit_cost': value['logCreditCost'],
        'space': value['space'],
    };
}

