/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { InventoryLocation } from './InventoryLocation';
import {
    InventoryLocationFromJSON,
    InventoryLocationFromJSONTyped,
    InventoryLocationToJSON,
} from './InventoryLocation';
import type { Unit } from './Unit';
import {
    UnitFromJSON,
    UnitFromJSONTyped,
    UnitToJSON,
} from './Unit';
import type { Food } from './Food';
import {
    FoodFromJSON,
    FoodFromJSONTyped,
    FoodToJSON,
} from './Food';

/**
 * Adds nested create feature
 * @export
 * @interface PatchedInventoryEntry
 */
export interface PatchedInventoryEntry {
    /**
     * 
     * @type {number}
     * @memberof PatchedInventoryEntry
     */
    id?: number;
    /**
     * 
     * @type {InventoryLocation}
     * @memberof PatchedInventoryEntry
     */
    inventoryLocation?: InventoryLocation;
    /**
     * 
     * @type {string}
     * @memberof PatchedInventoryEntry
     */
    subLocation?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedInventoryEntry
     */
    code?: string;
    /**
     * 
     * @type {Food}
     * @memberof PatchedInventoryEntry
     */
    food?: Food;
    /**
     * 
     * @type {Unit}
     * @memberof PatchedInventoryEntry
     */
    unit?: Unit;
    /**
     * 
     * @type {number}
     * @memberof PatchedInventoryEntry
     */
    amount?: number;
    /**
     * 
     * @type {Date}
     * @memberof PatchedInventoryEntry
     */
    expires?: Date;
    /**
     * 
     * @type {string}
     * @memberof PatchedInventoryEntry
     */
    note?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedInventoryEntry
     */
    readonly label?: string;
    /**
     * 
     * @type {Date}
     * @memberof PatchedInventoryEntry
     */
    readonly createdAt?: Date;
    /**
     * 
     * @type {number}
     * @memberof PatchedInventoryEntry
     */
    readonly createdBy?: number;
}

/**
 * Check if a given object implements the PatchedInventoryEntry interface.
 */
export function instanceOfPatchedInventoryEntry(value: object): value is PatchedInventoryEntry {
    return true;
}

export function PatchedInventoryEntryFromJSON(json: any): PatchedInventoryEntry {
    return PatchedInventoryEntryFromJSONTyped(json, false);
}

export function PatchedInventoryEntryFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedInventoryEntry {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'inventoryLocation': json['inventory_location'] == null ? undefined : InventoryLocationFromJSON(json['inventory_location']),
        'subLocation': json['sub_location'] == null ? undefined : json['sub_location'],
        'code': json['code'] == null ? undefined : json['code'],
        'food': json['food'] == null ? undefined : FoodFromJSON(json['food']),
        'unit': json['unit'] == null ? undefined : UnitFromJSON(json['unit']),
        'amount': json['amount'] == null ? undefined : json['amount'],
        'expires': json['expires'] == null ? undefined : (new Date(json['expires'])),
        'note': json['note'] == null ? undefined : json['note'],
        'label': json['label'] == null ? undefined : json['label'],
        'createdAt': json['created_at'] == null ? undefined : (new Date(json['created_at'])),
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
    };
}

export function PatchedInventoryEntryToJSON(value?: Omit<PatchedInventoryEntry, 'label'|'createdAt'|'createdBy'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'inventory_location': InventoryLocationToJSON(value['inventoryLocation']),
        'sub_location': value['subLocation'],
        'code': value['code'],
        'food': FoodToJSON(value['food']),
        'unit': UnitToJSON(value['unit']),
        'amount': value['amount'],
        'expires': value['expires'] == null ? undefined : ((value['expires'] as any).toISOString().substring(0,10)),
        'note': value['note'],
    };
}

