/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserRequest } from './UserRequest';
import {
    UserRequestFromJSON,
    UserRequestFromJSONTyped,
    UserRequestToJSON,
} from './UserRequest';

/**
 * Adds nested create feature
 * @export
 * @interface PatchedCustomFilterRequest
 */
export interface PatchedCustomFilterRequest {
    /**
     * 
     * @type {string}
     * @memberof PatchedCustomFilterRequest
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedCustomFilterRequest
     */
    search?: string;
    /**
     * 
     * @type {Array<UserRequest>}
     * @memberof PatchedCustomFilterRequest
     */
    shared?: Array<UserRequest>;
}

/**
 * Check if a given object implements the PatchedCustomFilterRequest interface.
 */
export function instanceOfPatchedCustomFilterRequest(value: object): boolean {
    return true;
}

export function PatchedCustomFilterRequestFromJSON(json: any): PatchedCustomFilterRequest {
    return PatchedCustomFilterRequestFromJSONTyped(json, false);
}

export function PatchedCustomFilterRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedCustomFilterRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'search': json['search'] == null ? undefined : json['search'],
        'shared': json['shared'] == null ? undefined : ((json['shared'] as Array<any>).map(UserRequestFromJSON)),
    };
}

export function PatchedCustomFilterRequestToJSON(value?: PatchedCustomFilterRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'search': value['search'],
        'shared': value['shared'] == null ? undefined : ((value['shared'] as Array<any>).map(UserRequestToJSON)),
    };
}

