/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { OpenDataUnit } from './OpenDataUnit';
import {
    OpenDataUnitFromJSON,
    OpenDataUnitFromJSONTyped,
    OpenDataUnitToJSON,
} from './OpenDataUnit';
import type { OpenDataFood } from './OpenDataFood';
import {
    OpenDataFoodFromJSON,
    OpenDataFoodFromJSONTyped,
    OpenDataFoodToJSON,
} from './OpenDataFood';
import type { OpenDataVersion } from './OpenDataVersion';
import {
    OpenDataVersionFromJSON,
    OpenDataVersionFromJSONTyped,
    OpenDataVersionToJSON,
} from './OpenDataVersion';

/**
 * Adds nested create feature
 * @export
 * @interface PatchedOpenDataConversion
 */
export interface PatchedOpenDataConversion {
    /**
     * 
     * @type {number}
     * @memberof PatchedOpenDataConversion
     */
    id?: number;
    /**
     * 
     * @type {OpenDataVersion}
     * @memberof PatchedOpenDataConversion
     */
    version?: OpenDataVersion;
    /**
     * 
     * @type {string}
     * @memberof PatchedOpenDataConversion
     */
    slug?: string;
    /**
     * 
     * @type {OpenDataFood}
     * @memberof PatchedOpenDataConversion
     */
    food?: OpenDataFood;
    /**
     * 
     * @type {number}
     * @memberof PatchedOpenDataConversion
     */
    baseAmount?: number;
    /**
     * 
     * @type {OpenDataUnit}
     * @memberof PatchedOpenDataConversion
     */
    baseUnit?: OpenDataUnit;
    /**
     * 
     * @type {number}
     * @memberof PatchedOpenDataConversion
     */
    convertedAmount?: number;
    /**
     * 
     * @type {OpenDataUnit}
     * @memberof PatchedOpenDataConversion
     */
    convertedUnit?: OpenDataUnit;
    /**
     * 
     * @type {string}
     * @memberof PatchedOpenDataConversion
     */
    source?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedOpenDataConversion
     */
    comment?: string;
    /**
     * 
     * @type {string}
     * @memberof PatchedOpenDataConversion
     */
    readonly createdBy?: string;
}

/**
 * Check if a given object implements the PatchedOpenDataConversion interface.
 */
export function instanceOfPatchedOpenDataConversion(value: object): value is PatchedOpenDataConversion {
    return true;
}

export function PatchedOpenDataConversionFromJSON(json: any): PatchedOpenDataConversion {
    return PatchedOpenDataConversionFromJSONTyped(json, false);
}

export function PatchedOpenDataConversionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedOpenDataConversion {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'version': json['version'] == null ? undefined : OpenDataVersionFromJSON(json['version']),
        'slug': json['slug'] == null ? undefined : json['slug'],
        'food': json['food'] == null ? undefined : OpenDataFoodFromJSON(json['food']),
        'baseAmount': json['base_amount'] == null ? undefined : json['base_amount'],
        'baseUnit': json['base_unit'] == null ? undefined : OpenDataUnitFromJSON(json['base_unit']),
        'convertedAmount': json['converted_amount'] == null ? undefined : json['converted_amount'],
        'convertedUnit': json['converted_unit'] == null ? undefined : OpenDataUnitFromJSON(json['converted_unit']),
        'source': json['source'] == null ? undefined : json['source'],
        'comment': json['comment'] == null ? undefined : json['comment'],
        'createdBy': json['created_by'] == null ? undefined : json['created_by'],
    };
}

export function PatchedOpenDataConversionToJSON(value?: Omit<PatchedOpenDataConversion, 'createdBy'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'version': OpenDataVersionToJSON(value['version']),
        'slug': value['slug'],
        'food': OpenDataFoodToJSON(value['food']),
        'base_amount': value['baseAmount'],
        'base_unit': OpenDataUnitToJSON(value['baseUnit']),
        'converted_amount': value['convertedAmount'],
        'converted_unit': OpenDataUnitToJSON(value['convertedUnit']),
        'source': value['source'],
        'comment': value['comment'],
    };
}

