/* tslint:disable */
/* eslint-disable */
/**
 * Django Recipes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RecipeStepsInnerFile
 */
export interface RecipeStepsInnerFile {
    /**
     * 
     * @type {number}
     * @memberof RecipeStepsInnerFile
     */
    readonly id?: number;
    /**
     * 
     * @type {string}
     * @memberof RecipeStepsInnerFile
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeStepsInnerFile
     */
    readonly fileDownload?: string;
    /**
     * 
     * @type {string}
     * @memberof RecipeStepsInnerFile
     */
    readonly preview?: string;
}

/**
 * Check if a given object implements the RecipeStepsInnerFile interface.
 */
export function instanceOfRecipeStepsInnerFile(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function RecipeStepsInnerFileFromJSON(json: any): RecipeStepsInnerFile {
    return RecipeStepsInnerFileFromJSONTyped(json, false);
}

export function RecipeStepsInnerFileFromJSONTyped(json: any, ignoreDiscriminator: boolean): RecipeStepsInnerFile {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'name': json['name'],
        'fileDownload': !exists(json, 'file_download') ? undefined : json['file_download'],
        'preview': !exists(json, 'preview') ? undefined : json['preview'],
    };
}

export function RecipeStepsInnerFileToJSON(value?: RecipeStepsInnerFile | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
    };
}

