/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `LINEAR` - Linear
 * * `DIAMETER` - Diameter
 * @export
 */
export const ScalingEnum = {
    Linear: 'LINEAR',
    Diameter: 'DIAMETER'
} as const;
export type ScalingEnum = typeof ScalingEnum[keyof typeof ScalingEnum];


export function instanceOfScalingEnum(value: any): boolean {
    for (const key in ScalingEnum) {
        if (Object.prototype.hasOwnProperty.call(ScalingEnum, key)) {
            if (ScalingEnum[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ScalingEnumFromJSON(json: any): ScalingEnum {
    return ScalingEnumFromJSONTyped(json, false);
}

export function ScalingEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): ScalingEnum {
    return json as ScalingEnum;
}

export function ScalingEnumToJSON(value?: ScalingEnum | null): any {
    return value as any;
}

