/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SourceImportPropertyType
 */
export interface SourceImportPropertyType {
    /**
     * 
     * @type {number}
     * @memberof SourceImportPropertyType
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof SourceImportPropertyType
     */
    name: string;
}

/**
 * Check if a given object implements the SourceImportPropertyType interface.
 */
export function instanceOfSourceImportPropertyType(value: object): value is SourceImportPropertyType {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function SourceImportPropertyTypeFromJSON(json: any): SourceImportPropertyType {
    return SourceImportPropertyTypeFromJSONTyped(json, false);
}

export function SourceImportPropertyTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceImportPropertyType {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'],
    };
}

export function SourceImportPropertyTypeToJSON(value?: SourceImportPropertyType | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

