/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StripePortal
 */
export interface StripePortal {
    /**
     * 
     * @type {string}
     * @memberof StripePortal
     */
    portalUrl: string;
    /**
     * 
     * @type {string}
     * @memberof StripePortal
     */
    stripePublicKey: string;
}

/**
 * Check if a given object implements the StripePortal interface.
 */
export function instanceOfStripePortal(value: object): value is StripePortal {
    if (!('portalUrl' in value) || value['portalUrl'] === undefined) return false;
    if (!('stripePublicKey' in value) || value['stripePublicKey'] === undefined) return false;
    return true;
}

export function StripePortalFromJSON(json: any): StripePortal {
    return StripePortalFromJSONTyped(json, false);
}

export function StripePortalFromJSONTyped(json: any, ignoreDiscriminator: boolean): StripePortal {
    if (json == null) {
        return json;
    }
    return {
        
        'portalUrl': json['portal_url'],
        'stripePublicKey': json['stripe_public_key'],
    };
}

export function StripePortalToJSON(value?: StripePortal | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'portal_url': value['portalUrl'],
        'stripe_public_key': value['stripePublicKey'],
    };
}

