/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `LIGHT` - Light
 * * `DARK` - Dark
 * @export
 */
export const UserPreferenceNavTextColorEnum = {
    Light: 'LIGHT',
    Dark: 'DARK'
} as const;
export type UserPreferenceNavTextColorEnum = typeof UserPreferenceNavTextColorEnum[keyof typeof UserPreferenceNavTextColorEnum];


export function instanceOfUserPreferenceNavTextColorEnum(value: any): boolean {
    for (const key in UserPreferenceNavTextColorEnum) {
        if (Object.prototype.hasOwnProperty.call(UserPreferenceNavTextColorEnum, key)) {
            if (UserPreferenceNavTextColorEnum[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UserPreferenceNavTextColorEnumFromJSON(json: any): UserPreferenceNavTextColorEnum {
    return UserPreferenceNavTextColorEnumFromJSONTyped(json, false);
}

export function UserPreferenceNavTextColorEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPreferenceNavTextColorEnum {
    return json as UserPreferenceNavTextColorEnum;
}

export function UserPreferenceNavTextColorEnumToJSON(value?: UserPreferenceNavTextColorEnum | null): any {
    return value as any;
}

