name: Auto-update recipe-scrapers daily

on:
  schedule:
    - cron: '0 5 * * *'  # Daily at 5am UTC
  workflow_dispatch:

jobs:
  bump:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Get current recipe-scrapers version
        id: current
        run: |
          CURRENT=$(grep '^recipe-scrapers==' requirements.txt | cut -d '=' -f3)
          echo "current=$CURRENT" >> $GITHUB_OUTPUT

      - name: Get latest recipe-scrapers version from PyPI
        id: latest
        run: |
          LATEST=$(curl -s https://pypi.org/pypi/recipe-scrapers/json | jq -r .info.version)
          echo "latest=$LATEST" >> $GITHUB_OUTPUT

      - name: Compare versions
        id: compare
        run: |
          echo "Current: ${{ steps.current.outputs.current }}"
          echo "Latest:  ${{ steps.latest.outputs.latest }}"
          if [ "${{ steps.latest.outputs.latest }}" != "${{ steps.current.outputs.current }}" ]; then
            echo "update=true" >> $GITHUB_OUTPUT
          else
            echo "update=false" >> $GITHUB_OUTPUT
          fi

      - name: Stop if already up to date
        if: steps.compare.outputs.update == 'false'
        run: echo "recipe-scrapers is already up to date."

      - name: Update requirements.txt
        if: steps.compare.outputs.update == 'true'
        run: |
          sed -i 's/^recipe-scrapers==.*/recipe-scrapers==${{ steps.latest.outputs.latest }}/' requirements.txt

      - name: Commit updated requirements.txt
        if: steps.compare.outputs.update == 'true'
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: "chore: bump recipe-scrapers to ${{ steps.latest.outputs.latest }}"
          branch: bump-recipe-scrapers
          create_branch: true

      - name: Create PR with automerge label
        if: steps.compare.outputs.update == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          branch: bump-recipe-scrapers
          title: "chore: bump recipe-scrapers to ${{ steps.latest.outputs.latest }}"
          body: "Automated update of recipe-scrapers"
          delete-branch: true
          labels: |
            dependencies
            automerge
