name: Dependabot Auto-merge

on:
  pull_request_target:
    types: [labeled, opened]
  workflow_dispatch:

jobs:
  auto-merge:
    if: github.actor == 'dependabot[bot]' && contains(github.event.pull_request.labels.*.name, 'automerge') || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-approve PR
        uses: hmarr/auto-approve-action@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Enable auto-merge
        uses: alexwilson/enable-github-automerge-action@2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: "squash"
