name: Deploy Docker Image

on:
  push:
    tags:
    - '*'

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: AhnSeongHyun/action-tag-docker-build-push@v1.0.0
        with:
          repo_name: vabene1111/recipes
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
