name: publish dev image docker
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '!master'
jobs:
  build:
    if: github.repository_owner == 'vabene1111'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update version file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: recipes/version.py
          contents: |
            VERSION_NUMBER = 'develop'
            BUILD_REF = '${{ github.sha }}'
          write-mode: overwrite
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        working-directory: ./vue
        run: yarn install
      - name: Build dependencies
        working-directory: ./vue
        run: yarn build
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@2.13
        with:
          name: vabene1111/recipes
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
