name: publish beta raspi image docker
on:
  push:
    branches:
      - 'beta'
jobs:
  build:
    if: github.repository_owner == 'TandoorRecipes'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      # Update Version number
      - name: Update version file
        uses: DamianReeves/write-file-action@v1.0
        with:
          path: recipes/version.py
          contents: |
            VERSION_NUMBER = 'beta'
            BUILD_REF = '${{ github.sha }}'
          write-mode: overwrite
      # Build Vue frontend
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        working-directory: ./vue
        run: yarn install
      - name: Build dependencies
        working-directory: ./vue
        run: yarn build
      # Build container
      - name: Build and publish image
        uses: ilteoood/docker_buildx@master
        with:
          publish: true
          imageName: vabene1111/recipes
          tag: beta-raspi
          dockerFile: Dockerfile-raspi
          platform: linux/arm/v7
          dockerUser: ${{ secrets.DOCKER_USERNAME }}
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
      # Send discord notification
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_BETA_WEBHOOK }}
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: '🚀 The BETA Image has been updated! 🥳'