name: Validate Automerge Label

on:
  pull_request:
    types: [labeled]
  workflow_dispatch:

jobs:
  validate:
    if: github.event.label.name == 'automerge' && github.event.pull_request.user.login != 'dependabot[bot]' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Remove invalid automerge label
        uses: actions-ecosystem/action-remove-labels@v1
        with:
          labels: automerge
          
      - name: Add invalid label  
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: invalid
          
      - name: Comment restriction
        uses: peter-evans/create-or-update-comment@23ff15729ef2fc348714a3bb66d2f655ca9066f2  # v4.0.0
        with:
          body: |
            ⚠️ **Automerge Restriction Notice**
            
            The `automerge` label has been removed from this PR because it has restricted use. Only PRs created by `dependabot[bot]` are allowed to use the automerge functionality.
            
            If you believe this is an error, please contact a repository maintainer.