/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SupermarketCategory } from './SupermarketCategory';
import {
    SupermarketCategoryFromJSON,
    SupermarketCategoryFromJSONTyped,
    SupermarketCategoryToJSON,
} from './SupermarketCategory';

/**
 * 
 * @export
 * @interface PaginatedSupermarketCategoryList
 */
export interface PaginatedSupermarketCategoryList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedSupermarketCategoryList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSupermarketCategoryList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedSupermarketCategoryList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<SupermarketCategory>}
     * @memberof PaginatedSupermarketCategoryList
     */
    results?: Array<SupermarketCategory>;
}

/**
 * Check if a given object implements the PaginatedSupermarketCategoryList interface.
 */
export function instanceOfPaginatedSupermarketCategoryList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedSupermarketCategoryListFromJSON(json: any): PaginatedSupermarketCategoryList {
    return PaginatedSupermarketCategoryListFromJSONTyped(json, false);
}

export function PaginatedSupermarketCategoryListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSupermarketCategoryList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(SupermarketCategoryFromJSON)),
    };
}

export function PaginatedSupermarketCategoryListToJSON(value?: PaginatedSupermarketCategoryList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(SupermarketCategoryToJSON)),
    };
}

