/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { CookLog } from './CookLog';
import {
    CookLogFromJSON,
    CookLogFromJSONTyped,
    CookLogToJSON,
} from './CookLog';

/**
 * 
 * @export
 * @interface PaginatedCookLogList
 */
export interface PaginatedCookLogList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedCookLogList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCookLogList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedCookLogList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<CookLog>}
     * @memberof PaginatedCookLogList
     */
    results?: Array<CookLog>;
}

/**
 * Check if a given object implements the PaginatedCookLogList interface.
 */
export function instanceOfPaginatedCookLogList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedCookLogListFromJSON(json: any): PaginatedCookLogList {
    return PaginatedCookLogListFromJSONTyped(json, false);
}

export function PaginatedCookLogListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCookLogList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(CookLogFromJSON)),
    };
}

export function PaginatedCookLogListToJSON(value?: PaginatedCookLogList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(CookLogToJSON)),
    };
}

