/* tslint:disable */
/* eslint-disable */
/**
 * Tandoor
 * Tandoor API Docs
 *
 * The version of the OpenAPI document: 0.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { MealPlan } from './MealPlan';
import {
    MealPlanFromJSON,
    MealPlanFromJSONTyped,
    MealPlanToJSON,
} from './MealPlan';

/**
 * 
 * @export
 * @interface PaginatedMealPlanList
 */
export interface PaginatedMealPlanList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedMealPlanList
     */
    count?: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedMealPlanList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedMealPlanList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<MealPlan>}
     * @memberof PaginatedMealPlanList
     */
    results?: Array<MealPlan>;
}

/**
 * Check if a given object implements the PaginatedMealPlanList interface.
 */
export function instanceOfPaginatedMealPlanList(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PaginatedMealPlanListFromJSON(json: any): PaginatedMealPlanList {
    return PaginatedMealPlanListFromJSONTyped(json, false);
}

export function PaginatedMealPlanListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedMealPlanList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'count': !exists(json, 'count') ? undefined : json['count'],
        'next': !exists(json, 'next') ? undefined : json['next'],
        'previous': !exists(json, 'previous') ? undefined : json['previous'],
        'results': !exists(json, 'results') ? undefined : ((json['results'] as Array<any>).map(MealPlanFromJSON)),
    };
}

export function PaginatedMealPlanListToJSON(value?: PaginatedMealPlanList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'count': value.count,
        'next': value.next,
        'previous': value.previous,
        'results': value.results === undefined ? undefined : ((value.results as Array<any>).map(MealPlanToJSON)),
    };
}

