kind: Secret
apiVersion: v1
metadata:
  name: recipes
type: Opaque
data:
  # echo -n 'db-password' | base64
  postgresql-password: ZGItcGFzc3dvcmQ=
  # echo -n 'postgres-user-password' | base64
  postgresql-postgres-password: cG9zdGdyZXMtdXNlci1wYXNzd29yZA==
  # echo -n 'secret-key' | sha256sum | awk '{ printf $1 }' | base64
  secret-key: ODVkYmUxNWQ3NWVmOTMwOGM3YWUwZjMzYzdhMzI0Y2M2ZjRiZjUxOWEyZWQyZjMwMjdiZDMzYzE0MGE0ZjlhYQ==
